# -*- coding: utf-8 -*-
# Copyright 2024 The DLRover Authors. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: elastic_training.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16\x65lastic_training.proto\x12\x07\x65lastic"+\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t";\n\x07Message\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x11\n\tnode_type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c*d\n\x08TaskType\x12\x08\n\x04NONE\x10\x00\x12\x0c\n\x08TRAINING\x10\x01\x12\x0e\n\nEVALUATION\x10\x02\x12\x0e\n\nPREDICTION\x10\x03\x12\x08\n\x04WAIT\x10\x04\x12\x16\n\x12TRAIN_END_CALLBACK\x10\x05\x32\x62\n\x06Master\x12-\n\x06report\x12\x10.elastic.Message\x1a\x11.elastic.Response\x12)\n\x03get\x12\x10.elastic.Message\x1a\x10.elastic.Messageb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "elastic_training_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _globals["_TASKTYPE"]._serialized_start = 141
    _globals["_TASKTYPE"]._serialized_end = 241
    _globals["_RESPONSE"]._serialized_start = 35
    _globals["_RESPONSE"]._serialized_end = 78
    _globals["_MESSAGE"]._serialized_start = 80
    _globals["_MESSAGE"]._serialized_end = 139
    _globals["_MASTER"]._serialized_start = 243
    _globals["_MASTER"]._serialized_end = 341
# @@protoc_insertion_point(module_scope)
