---
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: [--settings-path, tfplus/, --skip, tfplus/third_party]
  - repo: local
  # rev: v1.6.0
    hooks:
      - id: cpplint
        name: cpplint
        entry: cpplint
        language: python
        args:
          - --recursive
          - --filter=-build/header_guard, -build/c++11, -build/include_subdir
          - tfplus/
  # - repo: https://github.com/pre-commit/mirrors-pylint
  - repo: local
    # rev: v2.13.9
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]   # Only run pylint on Python files
        args: [
          "--rcfile=tfplus/.pylint", # Link to your config file
          # "--ignore-patterns='(?!.*\\.py$).*'", # Only apply pylint to .py         
        ]
  - repo: local
    hooks:
      - id: copyright_checker
        name: copyright_checker
        entry: python tfplus/scripts/codestyle/copyright.py
        language: system
        files: \.(go|py|sh|cc|h|hpp)$
        exclude: \.(deepcopy.go|pb.go)$