---
name: pre-commit
description: run pre-commit to check codes
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
runs:
  using: 'docker'
  image: "easydl/easydl:ci"
  args:
    - "/bin/bash"
    - "-c"
    - "pre-commit run -a --show-diff-on-failure --color=always"
