---
name: pre-commit
description: run pre-commit to check codes
runs:
  using: 'docker'
  image: "easydl/easydl:ci"
  args:
    - "/bin/bash"
    - "-c"
    - "pre-commit run -a --show-diff-on-failure --color=always"
