version: "1.5"

stages:
  - 构建&发布到测试库
agent:
  docker:
    image: reg.docker.alibaba-inc.com/elasticdl/elasticdl:dev_aci  # 不要更改此镜像，否则有protobuf 版本问题。
onlyExecuteLastPipeline: true #同一个分支只执行一个ci

only:
  triggerType:
    - push
  targetBranch:
    - release

build_elasticdl_dev:
  stage: 构建&发布到测试库
  id: build
  component: pypi-artifact-uploader
  only:
    - master
  inputs:
    buildImage: reg.docker.alibaba-inc.com/elasticdl/elasticdl:dev_aci
    registry: "https://artifacts.antgroup-inc.cn/artifact/repositories/simple-dev" # yamllint disable-line rule:line-length
    workdir: ./
    buildCmd: "make -f dlrover/Makefile && python setup_internal.py bdist_wheel"
