coverage:
  precision: 2
  range:
    - 60.0
    - 80.0
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch:
      default:
        removed_code_behavior: fully_covered_patch
        target: 80.0
        threshold: 3.0
    project:
      default:
        removed_code_behavior: fully_covered_patch
        target: 80.0
        threshold: 3.0
ignore:
  - ^dlrover/trainer/torch/flash_checkpoint/megatron_dist_ckpt.py.*
  - ^dlrover/trainer/torch/node_check/utils.py.*
  - ^dlrover/proto.*
