coverage:
  precision: 2
  range:
  - 60.0
  - 80.0
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch:
      default:
        target: 80%
        threshold: 5%
        removed_code_behavior: fully_covered_patch
    project:
      default:
        target: 80%
        threshold: 5%
        removed_code_behavior: fully_covered_patch
