---
coverage:
  precision: 2
  range: 60..90
  round: down
  ignore:
    - "dlrover/trainer/torch/flash_checkpoint/megatron_dist_ckpt.py"
    - "dlrover/trainer/torch/node_check/utils.py"
    - "dlrover/proto"
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch:
      default:
        target: 90%
        threshold: 1%
        removed_code_behavior: fully_covered_patch
    project:
      default:
        target: 83%
        threshold: 2%
        removed_code_behavior: fully_covered_patch
