---
apiVersion: elastic.iml.github.io/v1alpha1
kind: ElasticJob
metadata:
  name: deepctr-sample
spec:
  distributionStrategy: ParameterServerStrategy
  resourceLimits:
    cpu: "12"
    memory: "20000Mi"
  replicaSpecs:
    ps:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              image: easydl/tf-estimator:iris_dnn_v0
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -c
                - "pip uninstall dlrover -y \
                  && pip install dlrover==0.1.0rc0.dev6 -U \
                  -i https://test.pypi.org/simple/ \
                  && pip install pyhocon \
                  && cd /usr/local/lib/python3.8/site-packages/\
                  dlrover/trainer/examples/estimator_executor \
                  && python -m dlrover.trainer.entry.local_entry \
                  --platform=Kubernetes --conf=conf.TrainConf \
                  --enable_auto_scaling=True"
              volumeMounts:
                - name: pvc-nas
                  mountPath: /nas
          volumes:
            - name: pvc-nas
              persistentVolumeClaim:
                claimName: pvc-nas
    worker:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              image: easydl/tf-estimator:iris_dnn_v0
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -c
                - "pip install dlrover==0.1.0 -U --force-reinstall\
                  && pip install pyhocon \
                  && cd /home/model_zoo/tf_estimator/deepfm\
                  && python -m dlrover.trainer.entry.local_entry \
                  --platform=Kubernetes --conf=conf.TrainConf \
                  --enable_auto_scaling=True"
              volumeMounts:
                - name: pvc-nas
                  mountPath: /nas
          volumes:
            - name: pvc-nas
              persistentVolumeClaim:
                claimName: pvc-nas
