apiVersion: elastic.iml.github.io/v1alpha1
kind: ElasticJob
metadata:
  name: torch-mnist
  namespace: dlrover
spec:
  distributionStrategy: AllreduceStrategy
  optimizeMode: single-job
  replicaSpecs:
    worker:
      replicas: 2
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              # yamllint disable-line rule:line-length
              image: registry.cn-hangzhou.aliyuncs.com/intell-ai/dlrover:torch113-mnist
              imagePullPolicy: Always
              command:
                - /bin/bash
                - -c
                - "torchrun --nnodes=1:$WORKER_NUM --nproc_per_node=1
                --max_restarts=3 \
                --rdzv_backend=c10d --rdzv_endpoint=$RDZV_ENDPOINT:2222 \
                model_zoo/pytorch/mnist_cnn.py \
                --training_data /data/mnist_png/training/ \
                --validation_data /data/mnist_png/testing/ "
    dlrover-master:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              imagePullPolicy: Always
