apiVersion: elastic.iml.github.io/v1alpha1
kind: ElasticJob
metadata:
  name: torch-mnist-fsdp
  namespace: dlrover
spec:
  distributionStrategy: AllreduceStrategy
  optimizeMode: single-job
  replicaSpecs:
    worker:
      replicas: 4
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              # yamllint disable-line rule:line-length
              image: registry.cn-hangzhou.aliyuncs.com/major333/dlrover:fsdp-test
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -c
                - >-
                  dlrover-run --nnodes=$WORKER_NUM --nproc_per_node=1 \
                  --max_restarts=1 model_zoo/pytorch/mnist.py --use_fsdp \
                  --num_epochs 20 --training_data /data/mnist_png/training/ \
                  --validation_data /data/mnist_png/testing/
              resources:
                limits:
                  cpu: "2"
                  memory: 8Gi
                  nvidia.com/gpu: '1'
                requests:
                  cpu: "2"
                  memory: 8Gi
                  nvidia.com/gpu: '1'
