apiVersion: elastic.iml.github.io/v1alpha1
kind: ElasticJob
metadata:
  name: torch-mnist-debug
  namespace: dlrover
spec:
  distributionStrategy: AllreduceStrategy
  optimizeMode: single-job
  replicaSpecs:
    worker:
      replicas: 4
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              # yamllint disable-line rule:line-length
              image: easydl/dlrover-train:test
              imagePullPolicy: Never
              command:
                - /bin/bash
                - -c
                - "dlrover-run --nnodes=$WORKER_NUM \
                  --nproc_per_node=2 --max_restarts=3  \
                  model_zoo/pytorch/mnist_cnn.py --num_epochs 2 \
                  --training_data /data/mnist_png/training/ \
                  --validation_data /data/mnist_png/testing/"
              resources:
                limits:
                  cpu: "1"
                  memory: 2Gi
                requests:
                  cpu: "1"
                  memory: 2Gi
    dlrover-master:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              imagePullPolicy: Never
              image: easydl/dlrover-master:test
