---
name: dlrover-client-test
description: run pytest to execute python test cases of dlrover-client
runs:
  using: 'docker'
  image: "python:3.8.16"
  args:
    - "/bin/bash"
    - "-c"
    - "pip install pytest protobuf==3.20 kubernetes grpcio-tools psutil \
&& python -m grpc_tools.protoc -I. \
dlrover/proto/*.proto --python_out=. --grpc_python_out=. \
&& pip install 'ray[default]' pydantic==1.10.10 \
&&  python -m pytest dlrover/client/tests"
