apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dlrover-leader-election-rolebinding
  namespace: dlrover
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dlrover-leader-election-role
subjects:
- kind: ServiceAccount
  name: dlrover-controller-manager
  namespace: dlrover