---
name: go-master-test
description: run gotest to execute go test cases of ElasticJob operator
runs:
  using: 'docker'
  image: "easydl/dlrover:ci"
  args:
    - "/bin/bash"
    - "-c"
    - "rm -rf /usr/local/go && \
wget -q https://go.dev/dl/go1.23.4.linux-amd64.tar.gz && \
tar -C /usr/local -xzf go1.23.4.linux-amd64.tar.gz && \
go install github.com/onsi/ginkgo/v2/ginkgo@v2.22.2 &&
cd go/master && ginkgo -v ./..."
