---
name: go-master-test
description: run gotest to execute go test cases of ElasticJob operator
runs:
  using: 'docker'
  image: "golang:1.23.4"
  args:
    - "/bin/bash"
    - "-c"
    - "go install github.com/onsi/ginkgo/v2/ginkgo@v2.22.2 && \
    cd go/master && ginkgo -v ./..."
