---
name: tfplus-pre-commit
description: run pre-commit to check codes for tfplus
runs:
  using: 'docker'
  image: "easydl/tfplus:tf213_dev"
  args:
    - "/bin/bash"
    - "-c"
    - "git config --global --add safe.directory '*' \
&& pip install pre-commit==2.21.0 \
&& sh tfplus/dev/scripts/pre-commit.sh"
