// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dlrover/proto/brain.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MetricsType int32

const (
	MetricsType_Training_Hyper_Params MetricsType = 0
	MetricsType_Workflow_Feature      MetricsType = 1
	MetricsType_Training_Set_Feature  MetricsType = 2
	MetricsType_Model_Feature         MetricsType = 3
	MetricsType_Runtime_Info          MetricsType = 4
	MetricsType_Job_Exit_Reason       MetricsType = 5
	MetricsType_Optimization_Result   MetricsType = 6
	MetricsType_Type                  MetricsType = 7
	MetricsType_Resource              MetricsType = 8
	MetricsType_Customized_Data       MetricsType = 9
	MetricsType_Optimization          MetricsType = 10
)

var MetricsType_name = map[int32]string{
	0:  "Training_Hyper_Params",
	1:  "Workflow_Feature",
	2:  "Training_Set_Feature",
	3:  "Model_Feature",
	4:  "Runtime_Info",
	5:  "Job_Exit_Reason",
	6:  "Optimization_Result",
	7:  "Type",
	8:  "Resource",
	9:  "Customized_Data",
	10: "Optimization",
}

var MetricsType_value = map[string]int32{
	"Training_Hyper_Params": 0,
	"Workflow_Feature":      1,
	"Training_Set_Feature":  2,
	"Model_Feature":         3,
	"Runtime_Info":          4,
	"Job_Exit_Reason":       5,
	"Optimization_Result":   6,
	"Type":                  7,
	"Resource":              8,
	"Customized_Data":       9,
	"Optimization":          10,
}

func (x MetricsType) String() string {
	return proto.EnumName(MetricsType_name, int32(x))
}

func (MetricsType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{0}
}

type TrainingHyperParams struct {
	BatchSize            int64    `protobuf:"varint,1,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	Epoch                int64    `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	MaxSteps             int64    `protobuf:"varint,3,opt,name=max_steps,json=maxSteps,proto3" json:"max_steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrainingHyperParams) Reset()         { *m = TrainingHyperParams{} }
func (m *TrainingHyperParams) String() string { return proto.CompactTextString(m) }
func (*TrainingHyperParams) ProtoMessage()    {}
func (*TrainingHyperParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{0}
}

func (m *TrainingHyperParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrainingHyperParams.Unmarshal(m, b)
}
func (m *TrainingHyperParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrainingHyperParams.Marshal(b, m, deterministic)
}
func (m *TrainingHyperParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainingHyperParams.Merge(m, src)
}
func (m *TrainingHyperParams) XXX_Size() int {
	return xxx_messageInfo_TrainingHyperParams.Size(m)
}
func (m *TrainingHyperParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainingHyperParams.DiscardUnknown(m)
}

var xxx_messageInfo_TrainingHyperParams proto.InternalMessageInfo

func (m *TrainingHyperParams) GetBatchSize() int64 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

func (m *TrainingHyperParams) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *TrainingHyperParams) GetMaxSteps() int64 {
	if m != nil {
		return m.MaxSteps
	}
	return 0
}

type WorkflowFeature struct {
	JobName              string   `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CodeAddress          string   `protobuf:"bytes,3,opt,name=code_address,json=codeAddress,proto3" json:"code_address,omitempty"`
	WorkflowId           string   `protobuf:"bytes,4,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	NodeId               string   `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	OdpsProject          string   `protobuf:"bytes,6,opt,name=odps_project,json=odpsProject,proto3" json:"odps_project,omitempty"`
	IsProd               bool     `protobuf:"varint,7,opt,name=is_prod,json=isProd,proto3" json:"is_prod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkflowFeature) Reset()         { *m = WorkflowFeature{} }
func (m *WorkflowFeature) String() string { return proto.CompactTextString(m) }
func (*WorkflowFeature) ProtoMessage()    {}
func (*WorkflowFeature) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{1}
}

func (m *WorkflowFeature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowFeature.Unmarshal(m, b)
}
func (m *WorkflowFeature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowFeature.Marshal(b, m, deterministic)
}
func (m *WorkflowFeature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowFeature.Merge(m, src)
}
func (m *WorkflowFeature) XXX_Size() int {
	return xxx_messageInfo_WorkflowFeature.Size(m)
}
func (m *WorkflowFeature) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowFeature.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowFeature proto.InternalMessageInfo

func (m *WorkflowFeature) GetJobName() string {
	if m != nil {
		return m.JobName
	}
	return ""
}

func (m *WorkflowFeature) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *WorkflowFeature) GetCodeAddress() string {
	if m != nil {
		return m.CodeAddress
	}
	return ""
}

func (m *WorkflowFeature) GetWorkflowId() string {
	if m != nil {
		return m.WorkflowId
	}
	return ""
}

func (m *WorkflowFeature) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *WorkflowFeature) GetOdpsProject() string {
	if m != nil {
		return m.OdpsProject
	}
	return ""
}

func (m *WorkflowFeature) GetIsProd() bool {
	if m != nil {
		return m.IsProd
	}
	return false
}

type TrainingSetFeature struct {
	DatasetSize          int64    `protobuf:"varint,1,opt,name=dataset_size,json=datasetSize,proto3" json:"dataset_size,omitempty"`
	DatasetName          string   `protobuf:"bytes,2,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	SparseItemCount      int64    `protobuf:"varint,3,opt,name=sparse_item_count,json=sparseItemCount,proto3" json:"sparse_item_count,omitempty"`
	SparseFeatures       string   `protobuf:"bytes,4,opt,name=sparse_features,json=sparseFeatures,proto3" json:"sparse_features,omitempty"`
	SparseFeatureGroups  string   `protobuf:"bytes,5,opt,name=sparse_feature_groups,json=sparseFeatureGroups,proto3" json:"sparse_feature_groups,omitempty"`
	SparseFeatureShapes  string   `protobuf:"bytes,6,opt,name=sparse_feature_shapes,json=sparseFeatureShapes,proto3" json:"sparse_feature_shapes,omitempty"`
	DenseFeatures        string   `protobuf:"bytes,7,opt,name=dense_features,json=denseFeatures,proto3" json:"dense_features,omitempty"`
	DenseFeatureShapes   string   `protobuf:"bytes,8,opt,name=dense_feature_shapes,json=denseFeatureShapes,proto3" json:"dense_feature_shapes,omitempty"`
	StorageSize          int64    `protobuf:"varint,9,opt,name=storage_size,json=storageSize,proto3" json:"storage_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrainingSetFeature) Reset()         { *m = TrainingSetFeature{} }
func (m *TrainingSetFeature) String() string { return proto.CompactTextString(m) }
func (*TrainingSetFeature) ProtoMessage()    {}
func (*TrainingSetFeature) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{2}
}

func (m *TrainingSetFeature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrainingSetFeature.Unmarshal(m, b)
}
func (m *TrainingSetFeature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrainingSetFeature.Marshal(b, m, deterministic)
}
func (m *TrainingSetFeature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainingSetFeature.Merge(m, src)
}
func (m *TrainingSetFeature) XXX_Size() int {
	return xxx_messageInfo_TrainingSetFeature.Size(m)
}
func (m *TrainingSetFeature) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainingSetFeature.DiscardUnknown(m)
}

var xxx_messageInfo_TrainingSetFeature proto.InternalMessageInfo

func (m *TrainingSetFeature) GetDatasetSize() int64 {
	if m != nil {
		return m.DatasetSize
	}
	return 0
}

func (m *TrainingSetFeature) GetDatasetName() string {
	if m != nil {
		return m.DatasetName
	}
	return ""
}

func (m *TrainingSetFeature) GetSparseItemCount() int64 {
	if m != nil {
		return m.SparseItemCount
	}
	return 0
}

func (m *TrainingSetFeature) GetSparseFeatures() string {
	if m != nil {
		return m.SparseFeatures
	}
	return ""
}

func (m *TrainingSetFeature) GetSparseFeatureGroups() string {
	if m != nil {
		return m.SparseFeatureGroups
	}
	return ""
}

func (m *TrainingSetFeature) GetSparseFeatureShapes() string {
	if m != nil {
		return m.SparseFeatureShapes
	}
	return ""
}

func (m *TrainingSetFeature) GetDenseFeatures() string {
	if m != nil {
		return m.DenseFeatures
	}
	return ""
}

func (m *TrainingSetFeature) GetDenseFeatureShapes() string {
	if m != nil {
		return m.DenseFeatureShapes
	}
	return ""
}

func (m *TrainingSetFeature) GetStorageSize() int64 {
	if m != nil {
		return m.StorageSize
	}
	return 0
}

type ModelFeature struct {
	VariableCount        int64            `protobuf:"varint,1,opt,name=variable_count,json=variableCount,proto3" json:"variable_count,omitempty"`
	OpCount              int64            `protobuf:"varint,2,opt,name=op_count,json=opCount,proto3" json:"op_count,omitempty"`
	EmbeddingDimension   int64            `protobuf:"varint,3,opt,name=embedding_dimension,json=embeddingDimension,proto3" json:"embedding_dimension,omitempty"`
	TotalVariableSize    int64            `protobuf:"varint,4,opt,name=total_variable_size,json=totalVariableSize,proto3" json:"total_variable_size,omitempty"`
	MaxVariableSize      int64            `protobuf:"varint,5,opt,name=max_variable_size,json=maxVariableSize,proto3" json:"max_variable_size,omitempty"`
	UpdateOpCount        int64            `protobuf:"varint,6,opt,name=update_op_count,json=updateOpCount,proto3" json:"update_op_count,omitempty"`
	ReadOpCount          int64            `protobuf:"varint,7,opt,name=read_op_count,json=readOpCount,proto3" json:"read_op_count,omitempty"`
	InputFetchDur        int64            `protobuf:"varint,8,opt,name=input_fetch_dur,json=inputFetchDur,proto3" json:"input_fetch_dur,omitempty"`
	Flops                int64            `protobuf:"varint,9,opt,name=flops,proto3" json:"flops,omitempty"`
	RecvOpCount          int64            `protobuf:"varint,10,opt,name=recv_op_count,json=recvOpCount,proto3" json:"recv_op_count,omitempty"`
	KvEmbeddingDims      []int64          `protobuf:"varint,11,rep,packed,name=kv_embedding_dims,json=kvEmbeddingDims,proto3" json:"kv_embedding_dims,omitempty"`
	TensorAllocBytes     map[string]int64 `protobuf:"bytes,12,rep,name=tensor_alloc_bytes,json=tensorAllocBytes,proto3" json:"tensor_alloc_bytes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ModelFeature) Reset()         { *m = ModelFeature{} }
func (m *ModelFeature) String() string { return proto.CompactTextString(m) }
func (*ModelFeature) ProtoMessage()    {}
func (*ModelFeature) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{3}
}

func (m *ModelFeature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelFeature.Unmarshal(m, b)
}
func (m *ModelFeature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelFeature.Marshal(b, m, deterministic)
}
func (m *ModelFeature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelFeature.Merge(m, src)
}
func (m *ModelFeature) XXX_Size() int {
	return xxx_messageInfo_ModelFeature.Size(m)
}
func (m *ModelFeature) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelFeature.DiscardUnknown(m)
}

var xxx_messageInfo_ModelFeature proto.InternalMessageInfo

func (m *ModelFeature) GetVariableCount() int64 {
	if m != nil {
		return m.VariableCount
	}
	return 0
}

func (m *ModelFeature) GetOpCount() int64 {
	if m != nil {
		return m.OpCount
	}
	return 0
}

func (m *ModelFeature) GetEmbeddingDimension() int64 {
	if m != nil {
		return m.EmbeddingDimension
	}
	return 0
}

func (m *ModelFeature) GetTotalVariableSize() int64 {
	if m != nil {
		return m.TotalVariableSize
	}
	return 0
}

func (m *ModelFeature) GetMaxVariableSize() int64 {
	if m != nil {
		return m.MaxVariableSize
	}
	return 0
}

func (m *ModelFeature) GetUpdateOpCount() int64 {
	if m != nil {
		return m.UpdateOpCount
	}
	return 0
}

func (m *ModelFeature) GetReadOpCount() int64 {
	if m != nil {
		return m.ReadOpCount
	}
	return 0
}

func (m *ModelFeature) GetInputFetchDur() int64 {
	if m != nil {
		return m.InputFetchDur
	}
	return 0
}

func (m *ModelFeature) GetFlops() int64 {
	if m != nil {
		return m.Flops
	}
	return 0
}

func (m *ModelFeature) GetRecvOpCount() int64 {
	if m != nil {
		return m.RecvOpCount
	}
	return 0
}

func (m *ModelFeature) GetKvEmbeddingDims() []int64 {
	if m != nil {
		return m.KvEmbeddingDims
	}
	return nil
}

func (m *ModelFeature) GetTensorAllocBytes() map[string]int64 {
	if m != nil {
		return m.TensorAllocBytes
	}
	return nil
}

type RuntimeInfo struct {
	GlobalStep           int64      `protobuf:"varint,1,opt,name=global_step,json=globalStep,proto3" json:"global_step,omitempty"`
	RunningPods          []*PodMeta `protobuf:"bytes,2,rep,name=running_pods,json=runningPods,proto3" json:"running_pods,omitempty"`
	TimeStamp            int64      `protobuf:"varint,3,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	Speed                float32    `protobuf:"fixed32,4,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RuntimeInfo) Reset()         { *m = RuntimeInfo{} }
func (m *RuntimeInfo) String() string { return proto.CompactTextString(m) }
func (*RuntimeInfo) ProtoMessage()    {}
func (*RuntimeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{4}
}

func (m *RuntimeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuntimeInfo.Unmarshal(m, b)
}
func (m *RuntimeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuntimeInfo.Marshal(b, m, deterministic)
}
func (m *RuntimeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuntimeInfo.Merge(m, src)
}
func (m *RuntimeInfo) XXX_Size() int {
	return xxx_messageInfo_RuntimeInfo.Size(m)
}
func (m *RuntimeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RuntimeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RuntimeInfo proto.InternalMessageInfo

func (m *RuntimeInfo) GetGlobalStep() int64 {
	if m != nil {
		return m.GlobalStep
	}
	return 0
}

func (m *RuntimeInfo) GetRunningPods() []*PodMeta {
	if m != nil {
		return m.RunningPods
	}
	return nil
}

func (m *RuntimeInfo) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *RuntimeInfo) GetSpeed() float32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type PodMeta struct {
	PodName              string   `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodIp                string   `protobuf:"bytes,2,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	NodeIp               string   `protobuf:"bytes,3,opt,name=node_ip,json=nodeIp,proto3" json:"node_ip,omitempty"`
	HostName             string   `protobuf:"bytes,4,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	Namespace            string   `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	IsMixed              bool     `protobuf:"varint,6,opt,name=is_mixed,json=isMixed,proto3" json:"is_mixed,omitempty"`
	MemUsage             float64  `protobuf:"fixed64,7,opt,name=mem_usage,json=memUsage,proto3" json:"mem_usage,omitempty"`
	CpuUsage             float64  `protobuf:"fixed64,8,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodMeta) Reset()         { *m = PodMeta{} }
func (m *PodMeta) String() string { return proto.CompactTextString(m) }
func (*PodMeta) ProtoMessage()    {}
func (*PodMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{5}
}

func (m *PodMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodMeta.Unmarshal(m, b)
}
func (m *PodMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodMeta.Marshal(b, m, deterministic)
}
func (m *PodMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodMeta.Merge(m, src)
}
func (m *PodMeta) XXX_Size() int {
	return xxx_messageInfo_PodMeta.Size(m)
}
func (m *PodMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_PodMeta.DiscardUnknown(m)
}

var xxx_messageInfo_PodMeta proto.InternalMessageInfo

func (m *PodMeta) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *PodMeta) GetPodIp() string {
	if m != nil {
		return m.PodIp
	}
	return ""
}

func (m *PodMeta) GetNodeIp() string {
	if m != nil {
		return m.NodeIp
	}
	return ""
}

func (m *PodMeta) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *PodMeta) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PodMeta) GetIsMixed() bool {
	if m != nil {
		return m.IsMixed
	}
	return false
}

func (m *PodMeta) GetMemUsage() float64 {
	if m != nil {
		return m.MemUsage
	}
	return 0
}

func (m *PodMeta) GetCpuUsage() float64 {
	if m != nil {
		return m.CpuUsage
	}
	return 0
}

type JobMeta struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	User                 string   `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Cluster              string   `protobuf:"bytes,4,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Namespace            string   `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobMeta) Reset()         { *m = JobMeta{} }
func (m *JobMeta) String() string { return proto.CompactTextString(m) }
func (*JobMeta) ProtoMessage()    {}
func (*JobMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{6}
}

func (m *JobMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobMeta.Unmarshal(m, b)
}
func (m *JobMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobMeta.Marshal(b, m, deterministic)
}
func (m *JobMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobMeta.Merge(m, src)
}
func (m *JobMeta) XXX_Size() int {
	return xxx_messageInfo_JobMeta.Size(m)
}
func (m *JobMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_JobMeta.DiscardUnknown(m)
}

var xxx_messageInfo_JobMeta proto.InternalMessageInfo

func (m *JobMeta) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *JobMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobMeta) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *JobMeta) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *JobMeta) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type JobMetrics struct {
	DataStore   string      `protobuf:"bytes,1,opt,name=data_store,json=dataStore,proto3" json:"data_store,omitempty"`
	JobMeta     *JobMeta    `protobuf:"bytes,2,opt,name=job_meta,json=jobMeta,proto3" json:"job_meta,omitempty"`
	MetricsType MetricsType `protobuf:"varint,3,opt,name=metrics_type,json=metricsType,proto3,enum=proto.MetricsType" json:"metrics_type,omitempty"`
	// Types that are valid to be assigned to Metrics:
	//	*JobMetrics_TrainingHyperParams
	//	*JobMetrics_WorkflowFeature
	//	*JobMetrics_TrainingSetFeature
	//	*JobMetrics_ModelFeature
	//	*JobMetrics_RuntimeInfo
	//	*JobMetrics_JobExitReason
	//	*JobMetrics_ExtraInfo
	//	*JobMetrics_Type
	//	*JobMetrics_Resource
	//	*JobMetrics_CustomizedData
	//	*JobMetrics_JobOptimization
	Metrics              isJobMetrics_Metrics `protobuf_oneof:"metrics"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *JobMetrics) Reset()         { *m = JobMetrics{} }
func (m *JobMetrics) String() string { return proto.CompactTextString(m) }
func (*JobMetrics) ProtoMessage()    {}
func (*JobMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{7}
}

func (m *JobMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobMetrics.Unmarshal(m, b)
}
func (m *JobMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobMetrics.Marshal(b, m, deterministic)
}
func (m *JobMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobMetrics.Merge(m, src)
}
func (m *JobMetrics) XXX_Size() int {
	return xxx_messageInfo_JobMetrics.Size(m)
}
func (m *JobMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_JobMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_JobMetrics proto.InternalMessageInfo

func (m *JobMetrics) GetDataStore() string {
	if m != nil {
		return m.DataStore
	}
	return ""
}

func (m *JobMetrics) GetJobMeta() *JobMeta {
	if m != nil {
		return m.JobMeta
	}
	return nil
}

func (m *JobMetrics) GetMetricsType() MetricsType {
	if m != nil {
		return m.MetricsType
	}
	return MetricsType_Training_Hyper_Params
}

type isJobMetrics_Metrics interface {
	isJobMetrics_Metrics()
}

type JobMetrics_TrainingHyperParams struct {
	TrainingHyperParams *TrainingHyperParams `protobuf:"bytes,4,opt,name=training_hyper_params,json=trainingHyperParams,proto3,oneof"`
}

type JobMetrics_WorkflowFeature struct {
	WorkflowFeature *WorkflowFeature `protobuf:"bytes,5,opt,name=workflow_feature,json=workflowFeature,proto3,oneof"`
}

type JobMetrics_TrainingSetFeature struct {
	TrainingSetFeature *TrainingSetFeature `protobuf:"bytes,6,opt,name=training_set_feature,json=trainingSetFeature,proto3,oneof"`
}

type JobMetrics_ModelFeature struct {
	ModelFeature *ModelFeature `protobuf:"bytes,7,opt,name=model_feature,json=modelFeature,proto3,oneof"`
}

type JobMetrics_RuntimeInfo struct {
	RuntimeInfo *RuntimeInfo `protobuf:"bytes,8,opt,name=runtime_info,json=runtimeInfo,proto3,oneof"`
}

type JobMetrics_JobExitReason struct {
	JobExitReason string `protobuf:"bytes,9,opt,name=job_exit_reason,json=jobExitReason,proto3,oneof"`
}

type JobMetrics_ExtraInfo struct {
	ExtraInfo string `protobuf:"bytes,10,opt,name=extra_info,json=extraInfo,proto3,oneof"`
}

type JobMetrics_Type struct {
	Type string `protobuf:"bytes,11,opt,name=type,proto3,oneof"`
}

type JobMetrics_Resource struct {
	Resource string `protobuf:"bytes,12,opt,name=resource,proto3,oneof"`
}

type JobMetrics_CustomizedData struct {
	CustomizedData string `protobuf:"bytes,13,opt,name=customized_data,json=customizedData,proto3,oneof"`
}

type JobMetrics_JobOptimization struct {
	JobOptimization *JobOptimization `protobuf:"bytes,14,opt,name=job_optimization,json=jobOptimization,proto3,oneof"`
}

func (*JobMetrics_TrainingHyperParams) isJobMetrics_Metrics() {}

func (*JobMetrics_WorkflowFeature) isJobMetrics_Metrics() {}

func (*JobMetrics_TrainingSetFeature) isJobMetrics_Metrics() {}

func (*JobMetrics_ModelFeature) isJobMetrics_Metrics() {}

func (*JobMetrics_RuntimeInfo) isJobMetrics_Metrics() {}

func (*JobMetrics_JobExitReason) isJobMetrics_Metrics() {}

func (*JobMetrics_ExtraInfo) isJobMetrics_Metrics() {}

func (*JobMetrics_Type) isJobMetrics_Metrics() {}

func (*JobMetrics_Resource) isJobMetrics_Metrics() {}

func (*JobMetrics_CustomizedData) isJobMetrics_Metrics() {}

func (*JobMetrics_JobOptimization) isJobMetrics_Metrics() {}

func (m *JobMetrics) GetMetrics() isJobMetrics_Metrics {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *JobMetrics) GetTrainingHyperParams() *TrainingHyperParams {
	if x, ok := m.GetMetrics().(*JobMetrics_TrainingHyperParams); ok {
		return x.TrainingHyperParams
	}
	return nil
}

func (m *JobMetrics) GetWorkflowFeature() *WorkflowFeature {
	if x, ok := m.GetMetrics().(*JobMetrics_WorkflowFeature); ok {
		return x.WorkflowFeature
	}
	return nil
}

func (m *JobMetrics) GetTrainingSetFeature() *TrainingSetFeature {
	if x, ok := m.GetMetrics().(*JobMetrics_TrainingSetFeature); ok {
		return x.TrainingSetFeature
	}
	return nil
}

func (m *JobMetrics) GetModelFeature() *ModelFeature {
	if x, ok := m.GetMetrics().(*JobMetrics_ModelFeature); ok {
		return x.ModelFeature
	}
	return nil
}

func (m *JobMetrics) GetRuntimeInfo() *RuntimeInfo {
	if x, ok := m.GetMetrics().(*JobMetrics_RuntimeInfo); ok {
		return x.RuntimeInfo
	}
	return nil
}

func (m *JobMetrics) GetJobExitReason() string {
	if x, ok := m.GetMetrics().(*JobMetrics_JobExitReason); ok {
		return x.JobExitReason
	}
	return ""
}

func (m *JobMetrics) GetExtraInfo() string {
	if x, ok := m.GetMetrics().(*JobMetrics_ExtraInfo); ok {
		return x.ExtraInfo
	}
	return ""
}

func (m *JobMetrics) GetType() string {
	if x, ok := m.GetMetrics().(*JobMetrics_Type); ok {
		return x.Type
	}
	return ""
}

func (m *JobMetrics) GetResource() string {
	if x, ok := m.GetMetrics().(*JobMetrics_Resource); ok {
		return x.Resource
	}
	return ""
}

func (m *JobMetrics) GetCustomizedData() string {
	if x, ok := m.GetMetrics().(*JobMetrics_CustomizedData); ok {
		return x.CustomizedData
	}
	return ""
}

func (m *JobMetrics) GetJobOptimization() *JobOptimization {
	if x, ok := m.GetMetrics().(*JobMetrics_JobOptimization); ok {
		return x.JobOptimization
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*JobMetrics) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*JobMetrics_TrainingHyperParams)(nil),
		(*JobMetrics_WorkflowFeature)(nil),
		(*JobMetrics_TrainingSetFeature)(nil),
		(*JobMetrics_ModelFeature)(nil),
		(*JobMetrics_RuntimeInfo)(nil),
		(*JobMetrics_JobExitReason)(nil),
		(*JobMetrics_ExtraInfo)(nil),
		(*JobMetrics_Type)(nil),
		(*JobMetrics_Resource)(nil),
		(*JobMetrics_CustomizedData)(nil),
		(*JobMetrics_JobOptimization)(nil),
	}
}

type OptimizeConfig struct {
	OptimizerConfigRetriever string            `protobuf:"bytes,1,opt,name=optimizer_config_retriever,json=optimizerConfigRetriever,proto3" json:"optimizer_config_retriever,omitempty"`
	DataStore                string            `protobuf:"bytes,2,opt,name=data_store,json=dataStore,proto3" json:"data_store,omitempty"`
	BrainProcessor           string            `protobuf:"bytes,3,opt,name=brain_processor,json=brainProcessor,proto3" json:"brain_processor,omitempty"`
	CustomizedConfig         map[string]string `protobuf:"bytes,4,rep,name=customized_config,json=customizedConfig,proto3" json:"customized_config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral     struct{}          `json:"-"`
	XXX_unrecognized         []byte            `json:"-"`
	XXX_sizecache            int32             `json:"-"`
}

func (m *OptimizeConfig) Reset()         { *m = OptimizeConfig{} }
func (m *OptimizeConfig) String() string { return proto.CompactTextString(m) }
func (*OptimizeConfig) ProtoMessage()    {}
func (*OptimizeConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{8}
}

func (m *OptimizeConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptimizeConfig.Unmarshal(m, b)
}
func (m *OptimizeConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptimizeConfig.Marshal(b, m, deterministic)
}
func (m *OptimizeConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptimizeConfig.Merge(m, src)
}
func (m *OptimizeConfig) XXX_Size() int {
	return xxx_messageInfo_OptimizeConfig.Size(m)
}
func (m *OptimizeConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_OptimizeConfig.DiscardUnknown(m)
}

var xxx_messageInfo_OptimizeConfig proto.InternalMessageInfo

func (m *OptimizeConfig) GetOptimizerConfigRetriever() string {
	if m != nil {
		return m.OptimizerConfigRetriever
	}
	return ""
}

func (m *OptimizeConfig) GetDataStore() string {
	if m != nil {
		return m.DataStore
	}
	return ""
}

func (m *OptimizeConfig) GetBrainProcessor() string {
	if m != nil {
		return m.BrainProcessor
	}
	return ""
}

func (m *OptimizeConfig) GetCustomizedConfig() map[string]string {
	if m != nil {
		return m.CustomizedConfig
	}
	return nil
}

type PodState struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uid                  string            `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Type                 string            `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	IsOom                bool              `protobuf:"varint,4,opt,name=is_oom,json=isOom,proto3" json:"is_oom,omitempty"`
	Resource             *PodResource      `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource,omitempty"`
	UsedResource         *PodResource      `protobuf:"bytes,6,opt,name=used_resource,json=usedResource,proto3" json:"used_resource,omitempty"`
	CustomizedData       map[string]string `protobuf:"bytes,7,rep,name=customized_data,json=customizedData,proto3" json:"customized_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PodState) Reset()         { *m = PodState{} }
func (m *PodState) String() string { return proto.CompactTextString(m) }
func (*PodState) ProtoMessage()    {}
func (*PodState) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{9}
}

func (m *PodState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodState.Unmarshal(m, b)
}
func (m *PodState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodState.Marshal(b, m, deterministic)
}
func (m *PodState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodState.Merge(m, src)
}
func (m *PodState) XXX_Size() int {
	return xxx_messageInfo_PodState.Size(m)
}
func (m *PodState) XXX_DiscardUnknown() {
	xxx_messageInfo_PodState.DiscardUnknown(m)
}

var xxx_messageInfo_PodState proto.InternalMessageInfo

func (m *PodState) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PodState) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PodState) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PodState) GetIsOom() bool {
	if m != nil {
		return m.IsOom
	}
	return false
}

func (m *PodState) GetResource() *PodResource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *PodState) GetUsedResource() *PodResource {
	if m != nil {
		return m.UsedResource
	}
	return nil
}

func (m *PodState) GetCustomizedData() map[string]string {
	if m != nil {
		return m.CustomizedData
	}
	return nil
}

type JobState struct {
	Timestamp            int64                `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Pods                 map[string]*PodState `protobuf:"bytes,2,rep,name=pods,proto3" json:"pods,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Speed                float32              `protobuf:"fixed32,3,opt,name=speed,proto3" json:"speed,omitempty"`
	CustomizedData       map[string]string    `protobuf:"bytes,4,rep,name=customized_data,json=customizedData,proto3" json:"customized_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *JobState) Reset()         { *m = JobState{} }
func (m *JobState) String() string { return proto.CompactTextString(m) }
func (*JobState) ProtoMessage()    {}
func (*JobState) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{10}
}

func (m *JobState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobState.Unmarshal(m, b)
}
func (m *JobState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobState.Marshal(b, m, deterministic)
}
func (m *JobState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobState.Merge(m, src)
}
func (m *JobState) XXX_Size() int {
	return xxx_messageInfo_JobState.Size(m)
}
func (m *JobState) XXX_DiscardUnknown() {
	xxx_messageInfo_JobState.DiscardUnknown(m)
}

var xxx_messageInfo_JobState proto.InternalMessageInfo

func (m *JobState) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *JobState) GetPods() map[string]*PodState {
	if m != nil {
		return m.Pods
	}
	return nil
}

func (m *JobState) GetSpeed() float32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *JobState) GetCustomizedData() map[string]string {
	if m != nil {
		return m.CustomizedData
	}
	return nil
}

type OptimizeJobMeta struct {
	Uid                  string    `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Cluster              string    `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Namespace            string    `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	State                *JobState `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *OptimizeJobMeta) Reset()         { *m = OptimizeJobMeta{} }
func (m *OptimizeJobMeta) String() string { return proto.CompactTextString(m) }
func (*OptimizeJobMeta) ProtoMessage()    {}
func (*OptimizeJobMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{11}
}

func (m *OptimizeJobMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptimizeJobMeta.Unmarshal(m, b)
}
func (m *OptimizeJobMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptimizeJobMeta.Marshal(b, m, deterministic)
}
func (m *OptimizeJobMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptimizeJobMeta.Merge(m, src)
}
func (m *OptimizeJobMeta) XXX_Size() int {
	return xxx_messageInfo_OptimizeJobMeta.Size(m)
}
func (m *OptimizeJobMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_OptimizeJobMeta.DiscardUnknown(m)
}

var xxx_messageInfo_OptimizeJobMeta proto.InternalMessageInfo

func (m *OptimizeJobMeta) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OptimizeJobMeta) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *OptimizeJobMeta) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *OptimizeJobMeta) GetState() *JobState {
	if m != nil {
		return m.State
	}
	return nil
}

type OptimizeRequest struct {
	Type                 string             `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Config               *OptimizeConfig    `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Jobs                 []*OptimizeJobMeta `protobuf:"bytes,3,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *OptimizeRequest) Reset()         { *m = OptimizeRequest{} }
func (m *OptimizeRequest) String() string { return proto.CompactTextString(m) }
func (*OptimizeRequest) ProtoMessage()    {}
func (*OptimizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{12}
}

func (m *OptimizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptimizeRequest.Unmarshal(m, b)
}
func (m *OptimizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptimizeRequest.Marshal(b, m, deterministic)
}
func (m *OptimizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptimizeRequest.Merge(m, src)
}
func (m *OptimizeRequest) XXX_Size() int {
	return xxx_messageInfo_OptimizeRequest.Size(m)
}
func (m *OptimizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OptimizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OptimizeRequest proto.InternalMessageInfo

func (m *OptimizeRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *OptimizeRequest) GetConfig() *OptimizeConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *OptimizeRequest) GetJobs() []*OptimizeJobMeta {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type PodResource struct {
	Memory               int64    `protobuf:"varint,1,opt,name=memory,proto3" json:"memory,omitempty"`
	Cpu                  float32  `protobuf:"fixed32,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Gpu                  float32  `protobuf:"fixed32,3,opt,name=gpu,proto3" json:"gpu,omitempty"`
	GpuType              string   `protobuf:"bytes,4,opt,name=gpu_type,json=gpuType,proto3" json:"gpu_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodResource) Reset()         { *m = PodResource{} }
func (m *PodResource) String() string { return proto.CompactTextString(m) }
func (*PodResource) ProtoMessage()    {}
func (*PodResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{13}
}

func (m *PodResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodResource.Unmarshal(m, b)
}
func (m *PodResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodResource.Marshal(b, m, deterministic)
}
func (m *PodResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodResource.Merge(m, src)
}
func (m *PodResource) XXX_Size() int {
	return xxx_messageInfo_PodResource.Size(m)
}
func (m *PodResource) XXX_DiscardUnknown() {
	xxx_messageInfo_PodResource.DiscardUnknown(m)
}

var xxx_messageInfo_PodResource proto.InternalMessageInfo

func (m *PodResource) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *PodResource) GetCpu() float32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *PodResource) GetGpu() float32 {
	if m != nil {
		return m.Gpu
	}
	return 0
}

func (m *PodResource) GetGpuType() string {
	if m != nil {
		return m.GpuType
	}
	return ""
}

type TaskGroupResource struct {
	Count                int64        `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Resource             *PodResource `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TaskGroupResource) Reset()         { *m = TaskGroupResource{} }
func (m *TaskGroupResource) String() string { return proto.CompactTextString(m) }
func (*TaskGroupResource) ProtoMessage()    {}
func (*TaskGroupResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{14}
}

func (m *TaskGroupResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskGroupResource.Unmarshal(m, b)
}
func (m *TaskGroupResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskGroupResource.Marshal(b, m, deterministic)
}
func (m *TaskGroupResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskGroupResource.Merge(m, src)
}
func (m *TaskGroupResource) XXX_Size() int {
	return xxx_messageInfo_TaskGroupResource.Size(m)
}
func (m *TaskGroupResource) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskGroupResource.DiscardUnknown(m)
}

var xxx_messageInfo_TaskGroupResource proto.InternalMessageInfo

func (m *TaskGroupResource) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *TaskGroupResource) GetResource() *PodResource {
	if m != nil {
		return m.Resource
	}
	return nil
}

type JobResource struct {
	TaskGroupResources   map[string]*TaskGroupResource `protobuf:"bytes,1,rep,name=task_group_resources,json=taskGroupResources,proto3" json:"task_group_resources,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PodResources         map[string]*PodResource       `protobuf:"bytes,2,rep,name=pod_resources,json=podResources,proto3" json:"pod_resources,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *JobResource) Reset()         { *m = JobResource{} }
func (m *JobResource) String() string { return proto.CompactTextString(m) }
func (*JobResource) ProtoMessage()    {}
func (*JobResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{15}
}

func (m *JobResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobResource.Unmarshal(m, b)
}
func (m *JobResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobResource.Marshal(b, m, deterministic)
}
func (m *JobResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobResource.Merge(m, src)
}
func (m *JobResource) XXX_Size() int {
	return xxx_messageInfo_JobResource.Size(m)
}
func (m *JobResource) XXX_DiscardUnknown() {
	xxx_messageInfo_JobResource.DiscardUnknown(m)
}

var xxx_messageInfo_JobResource proto.InternalMessageInfo

func (m *JobResource) GetTaskGroupResources() map[string]*TaskGroupResource {
	if m != nil {
		return m.TaskGroupResources
	}
	return nil
}

func (m *JobResource) GetPodResources() map[string]*PodResource {
	if m != nil {
		return m.PodResources
	}
	return nil
}

type JobOptimizePlan struct {
	Timestamp            uint64           `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Resource             *JobResource     `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Job                  *OptimizeJobMeta `protobuf:"bytes,3,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *JobOptimizePlan) Reset()         { *m = JobOptimizePlan{} }
func (m *JobOptimizePlan) String() string { return proto.CompactTextString(m) }
func (*JobOptimizePlan) ProtoMessage()    {}
func (*JobOptimizePlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{16}
}

func (m *JobOptimizePlan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobOptimizePlan.Unmarshal(m, b)
}
func (m *JobOptimizePlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobOptimizePlan.Marshal(b, m, deterministic)
}
func (m *JobOptimizePlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobOptimizePlan.Merge(m, src)
}
func (m *JobOptimizePlan) XXX_Size() int {
	return xxx_messageInfo_JobOptimizePlan.Size(m)
}
func (m *JobOptimizePlan) XXX_DiscardUnknown() {
	xxx_messageInfo_JobOptimizePlan.DiscardUnknown(m)
}

var xxx_messageInfo_JobOptimizePlan proto.InternalMessageInfo

func (m *JobOptimizePlan) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *JobOptimizePlan) GetResource() *JobResource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *JobOptimizePlan) GetJob() *OptimizeJobMeta {
	if m != nil {
		return m.Job
	}
	return nil
}

type JobOptimization struct {
	Timestamp            int64            `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Config               *OptimizeConfig  `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Plan                 *JobOptimizePlan `protobuf:"bytes,3,opt,name=plan,proto3" json:"plan,omitempty"`
	JobStates            []*JobState      `protobuf:"bytes,4,rep,name=job_states,json=jobStates,proto3" json:"job_states,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *JobOptimization) Reset()         { *m = JobOptimization{} }
func (m *JobOptimization) String() string { return proto.CompactTextString(m) }
func (*JobOptimization) ProtoMessage()    {}
func (*JobOptimization) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{17}
}

func (m *JobOptimization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobOptimization.Unmarshal(m, b)
}
func (m *JobOptimization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobOptimization.Marshal(b, m, deterministic)
}
func (m *JobOptimization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobOptimization.Merge(m, src)
}
func (m *JobOptimization) XXX_Size() int {
	return xxx_messageInfo_JobOptimization.Size(m)
}
func (m *JobOptimization) XXX_DiscardUnknown() {
	xxx_messageInfo_JobOptimization.DiscardUnknown(m)
}

var xxx_messageInfo_JobOptimization proto.InternalMessageInfo

func (m *JobOptimization) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *JobOptimization) GetConfig() *OptimizeConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *JobOptimization) GetPlan() *JobOptimizePlan {
	if m != nil {
		return m.Plan
	}
	return nil
}

func (m *JobOptimization) GetJobStates() []*JobState {
	if m != nil {
		return m.JobStates
	}
	return nil
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{18}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type OptimizeResponse struct {
	Response             *Response          `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	JobOptimizePlans     []*JobOptimizePlan `protobuf:"bytes,2,rep,name=job_optimize_plans,json=jobOptimizePlans,proto3" json:"job_optimize_plans,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *OptimizeResponse) Reset()         { *m = OptimizeResponse{} }
func (m *OptimizeResponse) String() string { return proto.CompactTextString(m) }
func (*OptimizeResponse) ProtoMessage()    {}
func (*OptimizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{19}
}

func (m *OptimizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptimizeResponse.Unmarshal(m, b)
}
func (m *OptimizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptimizeResponse.Marshal(b, m, deterministic)
}
func (m *OptimizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptimizeResponse.Merge(m, src)
}
func (m *OptimizeResponse) XXX_Size() int {
	return xxx_messageInfo_OptimizeResponse.Size(m)
}
func (m *OptimizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OptimizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OptimizeResponse proto.InternalMessageInfo

func (m *OptimizeResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *OptimizeResponse) GetJobOptimizePlans() []*JobOptimizePlan {
	if m != nil {
		return m.JobOptimizePlans
	}
	return nil
}

type JobMetricsRequest struct {
	JobUuid              string   `protobuf:"bytes,1,opt,name=job_uuid,json=jobUuid,proto3" json:"job_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobMetricsRequest) Reset()         { *m = JobMetricsRequest{} }
func (m *JobMetricsRequest) String() string { return proto.CompactTextString(m) }
func (*JobMetricsRequest) ProtoMessage()    {}
func (*JobMetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{20}
}

func (m *JobMetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobMetricsRequest.Unmarshal(m, b)
}
func (m *JobMetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobMetricsRequest.Marshal(b, m, deterministic)
}
func (m *JobMetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobMetricsRequest.Merge(m, src)
}
func (m *JobMetricsRequest) XXX_Size() int {
	return xxx_messageInfo_JobMetricsRequest.Size(m)
}
func (m *JobMetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobMetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobMetricsRequest proto.InternalMessageInfo

func (m *JobMetricsRequest) GetJobUuid() string {
	if m != nil {
		return m.JobUuid
	}
	return ""
}

type JobMetricsResponse struct {
	Response             *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	JobMetrics           string    `protobuf:"bytes,2,opt,name=job_metrics,json=jobMetrics,proto3" json:"job_metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *JobMetricsResponse) Reset()         { *m = JobMetricsResponse{} }
func (m *JobMetricsResponse) String() string { return proto.CompactTextString(m) }
func (*JobMetricsResponse) ProtoMessage()    {}
func (*JobMetricsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb8c207265d2700, []int{21}
}

func (m *JobMetricsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobMetricsResponse.Unmarshal(m, b)
}
func (m *JobMetricsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobMetricsResponse.Marshal(b, m, deterministic)
}
func (m *JobMetricsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobMetricsResponse.Merge(m, src)
}
func (m *JobMetricsResponse) XXX_Size() int {
	return xxx_messageInfo_JobMetricsResponse.Size(m)
}
func (m *JobMetricsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobMetricsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobMetricsResponse proto.InternalMessageInfo

func (m *JobMetricsResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *JobMetricsResponse) GetJobMetrics() string {
	if m != nil {
		return m.JobMetrics
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.MetricsType", MetricsType_name, MetricsType_value)
	proto.RegisterType((*TrainingHyperParams)(nil), "proto.TrainingHyperParams")
	proto.RegisterType((*WorkflowFeature)(nil), "proto.WorkflowFeature")
	proto.RegisterType((*TrainingSetFeature)(nil), "proto.TrainingSetFeature")
	proto.RegisterType((*ModelFeature)(nil), "proto.ModelFeature")
	proto.RegisterMapType((map[string]int64)(nil), "proto.ModelFeature.TensorAllocBytesEntry")
	proto.RegisterType((*RuntimeInfo)(nil), "proto.RuntimeInfo")
	proto.RegisterType((*PodMeta)(nil), "proto.PodMeta")
	proto.RegisterType((*JobMeta)(nil), "proto.JobMeta")
	proto.RegisterType((*JobMetrics)(nil), "proto.JobMetrics")
	proto.RegisterType((*OptimizeConfig)(nil), "proto.OptimizeConfig")
	proto.RegisterMapType((map[string]string)(nil), "proto.OptimizeConfig.CustomizedConfigEntry")
	proto.RegisterType((*PodState)(nil), "proto.PodState")
	proto.RegisterMapType((map[string]string)(nil), "proto.PodState.CustomizedDataEntry")
	proto.RegisterType((*JobState)(nil), "proto.JobState")
	proto.RegisterMapType((map[string]string)(nil), "proto.JobState.CustomizedDataEntry")
	proto.RegisterMapType((map[string]*PodState)(nil), "proto.JobState.PodsEntry")
	proto.RegisterType((*OptimizeJobMeta)(nil), "proto.OptimizeJobMeta")
	proto.RegisterType((*OptimizeRequest)(nil), "proto.OptimizeRequest")
	proto.RegisterType((*PodResource)(nil), "proto.PodResource")
	proto.RegisterType((*TaskGroupResource)(nil), "proto.TaskGroupResource")
	proto.RegisterType((*JobResource)(nil), "proto.JobResource")
	proto.RegisterMapType((map[string]*PodResource)(nil), "proto.JobResource.PodResourcesEntry")
	proto.RegisterMapType((map[string]*TaskGroupResource)(nil), "proto.JobResource.TaskGroupResourcesEntry")
	proto.RegisterType((*JobOptimizePlan)(nil), "proto.JobOptimizePlan")
	proto.RegisterType((*JobOptimization)(nil), "proto.JobOptimization")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*OptimizeResponse)(nil), "proto.OptimizeResponse")
	proto.RegisterType((*JobMetricsRequest)(nil), "proto.JobMetricsRequest")
	proto.RegisterType((*JobMetricsResponse)(nil), "proto.JobMetricsResponse")
}

func init() { proto.RegisterFile("dlrover/proto/brain.proto", fileDescriptor_deb8c207265d2700) }

var fileDescriptor_deb8c207265d2700 = []byte{
	// 2195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x5f, 0x6f, 0x23, 0x49,
	0x11, 0x8f, 0xff, 0xdb, 0x65, 0x27, 0x76, 0x3a, 0xc9, 0xad, 0x93, 0x5b, 0xb4, 0xbb, 0x86, 0xbd,
	0xcb, 0xe6, 0x74, 0x5e, 0x08, 0x42, 0x87, 0x8e, 0x7d, 0xd9, 0xbf, 0x24, 0x2b, 0x96, 0x8d, 0x26,
	0x7b, 0x1c, 0x20, 0xa4, 0xd6, 0xd8, 0xd3, 0xf1, 0x8e, 0xe3, 0x99, 0x6e, 0xa6, 0x7b, 0xb2, 0xc9,
	0x4a, 0x48, 0x08, 0x89, 0x07, 0x9e, 0x91, 0xf8, 0x26, 0xbc, 0xf0, 0x09, 0x10, 0xef, 0xf7, 0xca,
	0x03, 0xe2, 0x09, 0xf1, 0x21, 0x50, 0x55, 0xf7, 0x8c, 0xc7, 0x8e, 0xf7, 0x96, 0x43, 0x3c, 0x79,
	0xba, 0xaa, 0xba, 0xba, 0xea, 0xd7, 0xf5, 0xaf, 0x0d, 0xbb, 0xc1, 0x2c, 0x91, 0x17, 0x22, 0xb9,
	0xaf, 0x12, 0x69, 0xe4, 0xfd, 0x51, 0xe2, 0x87, 0xf1, 0x90, 0xbe, 0x59, 0x8d, 0x7e, 0xf6, 0x3e,
	0x9c, 0x48, 0x39, 0x99, 0x09, 0x2b, 0x30, 0x4a, 0xcf, 0xee, 0x8b, 0x48, 0x99, 0x2b, 0x2b, 0x33,
	0x98, 0xc0, 0xd6, 0x2b, 0xdc, 0x12, 0xc6, 0x93, 0xa3, 0x2b, 0x25, 0x92, 0x13, 0x3f, 0xf1, 0x23,
	0xcd, 0xbe, 0x05, 0x30, 0xf2, 0xcd, 0xf8, 0x35, 0xd7, 0xe1, 0x5b, 0xd1, 0x2f, 0xdd, 0x2e, 0xed,
	0x57, 0xbc, 0x16, 0x51, 0x4e, 0xc3, 0xb7, 0x82, 0x6d, 0x43, 0x4d, 0x28, 0x39, 0x7e, 0xdd, 0x2f,
	0x13, 0xc7, 0x2e, 0xd8, 0x87, 0xd0, 0x8a, 0xfc, 0x4b, 0xae, 0x8d, 0x50, 0xba, 0x5f, 0x21, 0x4e,
	0x33, 0xf2, 0x2f, 0x4f, 0x71, 0x3d, 0xf8, 0x7b, 0x09, 0xba, 0x5f, 0xca, 0xe4, 0xfc, 0x6c, 0x26,
	0xdf, 0x3c, 0x13, 0xbe, 0x49, 0x13, 0xc1, 0x76, 0xa1, 0x39, 0x95, 0x23, 0x1e, 0xfb, 0x91, 0x3d,
	0xa3, 0xe5, 0x35, 0xa6, 0x72, 0xf4, 0x53, 0x3f, 0x12, 0xec, 0x06, 0x34, 0x52, 0x2d, 0x12, 0x1e,
	0x06, 0x74, 0x46, 0xcb, 0xab, 0xe3, 0xf2, 0x38, 0x60, 0x77, 0xa0, 0x33, 0x96, 0x81, 0xe0, 0x7e,
	0x10, 0x24, 0x42, 0xdb, 0x73, 0x5a, 0x5e, 0x1b, 0x69, 0x0f, 0x2d, 0x89, 0xdd, 0x82, 0xf6, 0x1b,
	0x77, 0x12, 0xee, 0xaf, 0x92, 0x04, 0x64, 0xa4, 0xe3, 0x00, 0x95, 0xc7, 0xa8, 0x23, 0x0c, 0xfa,
	0x35, 0xab, 0x1c, 0x97, 0x56, 0xb9, 0x0c, 0x94, 0xe6, 0x2a, 0x91, 0x53, 0x31, 0x36, 0xfd, 0xba,
	0x55, 0x8e, 0xb4, 0x13, 0x4b, 0xc2, 0xbd, 0x21, 0x09, 0x04, 0xfd, 0xc6, 0xed, 0xd2, 0x7e, 0xd3,
	0xab, 0x87, 0xc8, 0x0b, 0x06, 0x7f, 0xac, 0x00, 0xcb, 0xa0, 0x3c, 0x15, 0x26, 0xf3, 0xf1, 0x0e,
	0x74, 0x02, 0xdf, 0xf8, 0x5a, 0x98, 0x22, 0x96, 0x6d, 0x47, 0x23, 0x34, 0x0b, 0x22, 0x04, 0x85,
	0x75, 0x38, 0x13, 0x21, 0x38, 0x0e, 0x60, 0x53, 0x2b, 0x3f, 0xd1, 0x82, 0x87, 0x46, 0x44, 0x7c,
	0x2c, 0xd3, 0xd8, 0x38, 0x88, 0xbb, 0x96, 0x71, 0x6c, 0x44, 0xf4, 0x18, 0xc9, 0xec, 0x63, 0x70,
	0x24, 0x7e, 0x66, 0x6d, 0xd0, 0x0e, 0x82, 0x0d, 0x4b, 0x76, 0x96, 0x69, 0x76, 0x08, 0x3b, 0x8b,
	0x82, 0x7c, 0x92, 0xc8, 0x54, 0x69, 0x07, 0xca, 0xd6, 0x82, 0xf8, 0x8f, 0x89, 0xb5, 0x62, 0x8f,
	0x7e, 0xed, 0x2b, 0xa1, 0x1d, 0x54, 0x8b, 0x7b, 0x4e, 0x89, 0xc5, 0xee, 0xc2, 0x46, 0x20, 0xe2,
	0xa2, 0x3d, 0x0d, 0x12, 0x5e, 0x27, 0x6a, 0x6e, 0xce, 0x77, 0x61, 0x7b, 0x41, 0x2c, 0xd3, 0xdc,
	0x24, 0x61, 0x56, 0x14, 0x76, 0x8a, 0xef, 0x40, 0x47, 0x1b, 0x99, 0xf8, 0x13, 0x61, 0xb1, 0x6d,
	0x59, 0x6c, 0x1d, 0x0d, 0xb1, 0x1d, 0x7c, 0x55, 0x85, 0xce, 0x0b, 0x19, 0x88, 0x59, 0x76, 0x1f,
	0x77, 0x61, 0xe3, 0xc2, 0x4f, 0x42, 0x7f, 0x34, 0x13, 0x0e, 0x46, 0x7b, 0x23, 0xeb, 0x19, 0xd5,
	0x82, 0xb8, 0x0b, 0x4d, 0xa9, 0x9c, 0x80, 0x0d, 0xf2, 0x86, 0x54, 0x96, 0x75, 0x1f, 0xb6, 0x44,
	0x34, 0x12, 0x41, 0x10, 0xc6, 0x13, 0x1e, 0x84, 0x91, 0x88, 0x75, 0x28, 0x63, 0x77, 0x1b, 0x2c,
	0x67, 0x3d, 0xc9, 0x38, 0x6c, 0x08, 0x5b, 0x46, 0x1a, 0x7f, 0xc6, 0xf3, 0x83, 0xc9, 0xda, 0x2a,
	0x6d, 0xd8, 0x24, 0xd6, 0xcf, 0x1c, 0x87, 0xe2, 0xe1, 0x00, 0x36, 0x31, 0x8f, 0x16, 0xa5, 0x6b,
	0xf6, 0xb2, 0x23, 0xff, 0x72, 0x41, 0xf6, 0x23, 0xe8, 0xa6, 0x2a, 0xf0, 0x8d, 0xe0, 0xb9, 0xb9,
	0x75, 0xeb, 0x8f, 0x25, 0xbf, 0x74, 0x46, 0x0f, 0x60, 0x3d, 0x11, 0x7e, 0x30, 0x97, 0x6a, 0x58,
	0xac, 0x90, 0x98, 0xc9, 0x7c, 0x04, 0xdd, 0x30, 0x56, 0xa9, 0xe1, 0x67, 0x02, 0x53, 0x3f, 0x48,
	0x13, 0xc2, 0xbe, 0xe2, 0xad, 0x13, 0xf9, 0x19, 0x52, 0x9f, 0xa4, 0x09, 0x66, 0xff, 0xd9, 0x4c,
	0x2a, 0xed, 0xf0, 0xb6, 0x0b, 0x7b, 0xc2, 0xf8, 0x62, 0x7e, 0x02, 0x64, 0x27, 0x8c, 0x2f, 0xb2,
	0x13, 0x0e, 0x60, 0xf3, 0xfc, 0x82, 0x2f, 0xa0, 0xa7, 0xfb, 0xed, 0xdb, 0x15, 0xf4, 0xec, 0xfc,
	0xe2, 0x69, 0x01, 0x3a, 0xcd, 0xbe, 0x04, 0x66, 0x44, 0xac, 0x65, 0xc2, 0xfd, 0xd9, 0x4c, 0x8e,
	0xf9, 0xe8, 0xca, 0x08, 0xdd, 0xef, 0xdc, 0xae, 0xec, 0xb7, 0x0f, 0xef, 0xd9, 0xea, 0x35, 0x2c,
	0xde, 0xec, 0xf0, 0x15, 0x49, 0x3f, 0x44, 0xe1, 0x47, 0x28, 0xfb, 0x34, 0x36, 0xc9, 0x95, 0xd7,
	0x33, 0x4b, 0xe4, 0xbd, 0xc7, 0xb0, 0xb3, 0x52, 0x94, 0xf5, 0xa0, 0x72, 0x2e, 0xae, 0x5c, 0x25,
	0xc2, 0x4f, 0xf4, 0xf4, 0xc2, 0x9f, 0xa5, 0x22, 0xab, 0x73, 0xb4, 0xf8, 0xbc, 0xfc, 0xc3, 0xd2,
	0xe0, 0x4f, 0x25, 0x68, 0x7b, 0x69, 0x6c, 0xc2, 0x48, 0x1c, 0xc7, 0x67, 0x12, 0x6b, 0xce, 0x64,
	0x26, 0x47, 0xfe, 0x8c, 0xca, 0x9f, 0x8b, 0x29, 0xb0, 0x24, 0x2c, 0x80, 0xec, 0x7b, 0xd0, 0x49,
	0xd2, 0x18, 0x8b, 0x03, 0x57, 0x32, 0xd0, 0xfd, 0x32, 0x39, 0xb2, 0xe1, 0x1c, 0x39, 0x91, 0xc1,
	0x0b, 0x61, 0x7c, 0xaf, 0xed, 0x64, 0x4e, 0x64, 0x40, 0x45, 0x18, 0xf5, 0x73, 0x6d, 0xfc, 0x48,
	0xb9, 0xf8, 0x6a, 0x21, 0xe5, 0x14, 0x09, 0x68, 0x9c, 0x56, 0x42, 0xd8, 0x02, 0x57, 0xf6, 0xec,
	0x62, 0xf0, 0xcf, 0x12, 0x34, 0x9c, 0x36, 0x0c, 0x62, 0x25, 0x83, 0x85, 0xfa, 0xaa, 0x64, 0x40,
	0x05, 0x65, 0x07, 0xea, 0xc8, 0x0a, 0x95, 0xab, 0x36, 0x35, 0x25, 0x83, 0x63, 0x35, 0xaf, 0x8c,
	0xca, 0x15, 0x56, 0x5b, 0x19, 0x15, 0xd6, 0xf6, 0xd7, 0x52, 0xbb, 0x02, 0x65, 0xcb, 0x49, 0x13,
	0x09, 0xa4, 0xec, 0x26, 0xb4, 0x90, 0xae, 0x95, 0x3f, 0x16, 0xae, 0x78, 0xcc, 0x09, 0x68, 0x45,
	0xa8, 0x79, 0x14, 0x5e, 0x8a, 0x80, 0x62, 0xb3, 0xe9, 0x35, 0x42, 0xfd, 0x02, 0x97, 0xd4, 0x31,
	0x44, 0xc4, 0x53, 0xed, 0x4f, 0x04, 0x45, 0x64, 0xc9, 0x6b, 0x46, 0x22, 0xfa, 0x02, 0xd7, 0xc8,
	0x1c, 0xab, 0xd4, 0x31, 0x9b, 0x96, 0x39, 0x56, 0x29, 0x31, 0x07, 0xbf, 0x81, 0xc6, 0x73, 0x39,
	0x22, 0x2f, 0x19, 0x54, 0xd3, 0x34, 0x0c, 0x9c, 0x87, 0xf4, 0x8d, 0xb4, 0x42, 0x29, 0xa5, 0x6f,
	0x92, 0xd3, 0x22, 0x71, 0x8e, 0xd1, 0x37, 0xeb, 0x43, 0x63, 0x3c, 0x4b, 0xb5, 0x11, 0x89, 0x73,
	0x2a, 0x5b, 0x7e, 0xbd, 0x4f, 0x83, 0x7f, 0xd4, 0x00, 0xec, 0xf9, 0x49, 0x38, 0xa6, 0x9b, 0xc2,
	0x6a, 0xcd, 0xb1, 0xf2, 0x64, 0x50, 0xb7, 0x90, 0x72, 0x8a, 0x04, 0x76, 0xcf, 0xf6, 0xb9, 0x48,
	0x18, 0x9f, 0x2c, 0x9a, 0xdf, 0xbb, 0xf3, 0x81, 0xfa, 0x1e, 0x39, 0xf3, 0x03, 0xe8, 0x44, 0x56,
	0x29, 0x37, 0x57, 0x4a, 0x90, 0xb1, 0x1b, 0x87, 0x2c, 0x8b, 0x77, 0xcb, 0x7a, 0x75, 0xa5, 0x84,
	0xd7, 0x8e, 0xe6, 0x0b, 0x76, 0x02, 0x3b, 0xc6, 0xf5, 0x1e, 0xfe, 0x1a, 0xfb, 0x38, 0x57, 0xd4,
	0xc8, 0xc9, 0xab, 0xf6, 0xe1, 0x9e, 0xdb, 0xbf, 0xa2, 0xd5, 0x1f, 0xad, 0x79, 0x5b, 0x66, 0xc5,
	0x04, 0xf0, 0x18, 0x7a, 0x79, 0x13, 0x75, 0x05, 0x99, 0x60, 0x68, 0x1f, 0x7e, 0xe0, 0x94, 0x2d,
	0x75, 0xf3, 0xa3, 0x35, 0xaf, 0xfb, 0x66, 0xa9, 0xc1, 0xbf, 0x80, 0xed, 0xdc, 0x2c, 0x6c, 0x6f,
	0x99, 0xa2, 0x3a, 0x29, 0xda, 0x5d, 0xb2, 0x6a, 0xde, 0x35, 0x8f, 0xd6, 0x3c, 0x66, 0xae, 0xf7,
	0xd2, 0xcf, 0x61, 0x3d, 0xc2, 0x8c, 0xcf, 0xf5, 0x34, 0x48, 0xcf, 0xd6, 0x8a, 0x6a, 0x70, 0xb4,
	0xe6, 0x75, 0xa2, 0x62, 0xdd, 0xff, 0x8c, 0xf2, 0x8f, 0xf2, 0x29, 0x8c, 0xcf, 0x24, 0x05, 0x54,
	0x3b, 0x07, 0xb6, 0x90, 0xca, 0x47, 0x6b, 0x94, 0x85, 0x79, 0x66, 0xef, 0x43, 0x17, 0x2f, 0x4f,
	0x5c, 0x86, 0x86, 0x27, 0xc2, 0xd7, 0x32, 0xa6, 0xba, 0xd7, 0x3a, 0x5a, 0xf3, 0xd6, 0xa7, 0x72,
	0xf4, 0xf4, 0x32, 0x34, 0x1e, 0x91, 0xd9, 0x2d, 0x00, 0x71, 0x69, 0x12, 0xdf, 0x1e, 0x00, 0x4e,
	0xa8, 0x45, 0x34, 0x52, 0xb5, 0x0d, 0x55, 0xba, 0xd4, 0xb6, 0x63, 0xd1, 0x8a, 0xdd, 0x84, 0x66,
	0x22, 0xb4, 0x4c, 0x93, 0xb1, 0xe8, 0x77, 0x1c, 0x27, 0xa7, 0xb0, 0x7b, 0xd0, 0x1d, 0xa7, 0xda,
	0xc8, 0x28, 0x7c, 0x2b, 0x02, 0x8e, 0x31, 0xd5, 0x5f, 0x77, 0x42, 0x1b, 0x73, 0xc6, 0x13, 0xdf,
	0xf8, 0x78, 0x65, 0x68, 0xa9, 0x54, 0x26, 0x8c, 0xc2, 0xb7, 0xbe, 0xc1, 0xae, 0xb4, 0xb1, 0x70,
	0x65, 0xcf, 0xe5, 0xe8, 0x65, 0x81, 0x8b, 0x57, 0x36, 0x5d, 0x24, 0x3d, 0x6a, 0x41, 0xc3, 0x05,
	0xd6, 0xe0, 0xcf, 0x65, 0xd8, 0x70, 0x3c, 0xf1, 0x58, 0xc6, 0x67, 0xe1, 0x84, 0x3d, 0x80, 0x3d,
	0xa7, 0x5e, 0x24, 0x7c, 0x4c, 0x34, 0x9e, 0xa0, 0xb8, 0xb8, 0x10, 0x89, 0x0b, 0xfc, 0x7e, 0x2e,
	0x61, 0x37, 0x79, 0x19, 0x7f, 0x29, 0x4d, 0xca, 0xcb, 0x69, 0xf2, 0x31, 0x74, 0x69, 0x7c, 0xc5,
	0xe9, 0x6a, 0x2c, 0xb4, 0x96, 0x59, 0xae, 0x6e, 0x10, 0xf9, 0x24, 0xa3, 0xb2, 0x9f, 0xc3, 0x66,
	0x01, 0x13, 0x6b, 0x46, 0xbf, 0x4a, 0x05, 0xf5, 0x13, 0xe7, 0xe9, 0xa2, 0xdd, 0xc3, 0xc7, 0xb9,
	0xb8, 0x25, 0xb8, 0xde, 0x30, 0x5e, 0x22, 0x63, 0x6f, 0x58, 0x29, 0xfa, 0xbe, 0xde, 0xd0, 0x2a,
	0xf6, 0x86, 0xaf, 0xca, 0xd0, 0x3c, 0x91, 0xc1, 0xa9, 0xf1, 0x8d, 0xc8, 0x2b, 0x51, 0xa9, 0x50,
	0x89, 0x7a, 0x50, 0x49, 0xf3, 0xc1, 0xb6, 0xe2, 0xea, 0x55, 0x9e, 0xee, 0x2d, 0x17, 0x17, 0x3b,
	0x50, 0x0f, 0x35, 0x97, 0x32, 0xa2, 0x24, 0x6e, 0x7a, 0xb5, 0x50, 0xbf, 0x94, 0x11, 0x1b, 0x16,
	0xc2, 0xa5, 0xb6, 0x10, 0xc4, 0x27, 0x32, 0xf0, 0x1c, 0xa7, 0x10, 0x40, 0x9f, 0xc1, 0x7a, 0xaa,
	0x45, 0xc0, 0xf3, 0x4d, 0xf5, 0x77, 0x6e, 0xea, 0xa0, 0x60, 0xb6, 0x62, 0x3f, 0xb9, 0x1e, 0x79,
	0x0d, 0xc2, 0xf8, 0xdb, 0xf3, 0xad, 0xe4, 0x63, 0x01, 0x5d, 0x8c, 0x43, 0x8b, 0xed, 0x52, 0x70,
	0xee, 0x3d, 0x84, 0xad, 0x15, 0x62, 0xdf, 0x08, 0xd7, 0xbf, 0x96, 0xa1, 0xf9, 0x5c, 0x8e, 0x2c,
	0xae, 0x37, 0x81, 0x5a, 0xa1, 0xed, 0x8d, 0xa5, 0x79, 0x6f, 0x24, 0x02, 0xfb, 0x14, 0xaa, 0x85,
	0x2e, 0xbb, 0x3b, 0x0f, 0x7f, 0x6b, 0x30, 0xb6, 0x57, 0x6b, 0x26, 0x89, 0xcd, 0x5b, 0x69, 0xa5,
	0xd0, 0x4a, 0x57, 0x01, 0x50, 0x5d, 0x00, 0x20, 0xd7, 0xf7, 0xdf, 0x00, 0x70, 0x04, 0xad, 0xfc,
	0xd8, 0x15, 0x6e, 0xdf, 0x2d, 0xba, 0xdd, 0x3e, 0xec, 0x2e, 0x61, 0x5c, 0xc0, 0xe1, 0xff, 0x01,
	0xe5, 0xef, 0x4a, 0xd0, 0xcd, 0x52, 0x24, 0xeb, 0xa3, 0x2e, 0x2a, 0x4b, 0xf3, 0xa8, 0x2c, 0x74,
	0xc7, 0xf2, 0xd7, 0x74, 0xc7, 0xca, 0x72, 0xc7, 0xbf, 0x0b, 0x35, 0x8d, 0x46, 0xbb, 0xee, 0xd3,
	0x5d, 0x82, 0xcb, 0xb3, 0xdc, 0xc1, 0x6f, 0x0b, 0x46, 0x78, 0xe2, 0xd7, 0xa9, 0xd0, 0x26, 0x4f,
	0x84, 0x52, 0x21, 0x11, 0x3e, 0x85, 0xba, 0xcb, 0x71, 0x8b, 0xcd, 0xce, 0xca, 0x1c, 0xf7, 0x9c,
	0x10, 0x3b, 0x80, 0xea, 0x54, 0x8e, 0xf0, 0x65, 0x58, 0x29, 0x94, 0xbe, 0x25, 0x6f, 0x3d, 0x92,
	0x19, 0x04, 0xd0, 0x2e, 0x24, 0x00, 0xfb, 0x00, 0xea, 0x91, 0x88, 0x64, 0x72, 0xe5, 0x22, 0xca,
	0xad, 0x10, 0x9a, 0xb1, 0x4a, 0xe9, 0xf8, 0xb2, 0x87, 0x9f, 0x48, 0x99, 0xa8, 0xd4, 0xc5, 0x0b,
	0x7e, 0xe2, 0x98, 0x33, 0x51, 0xa9, 0xed, 0xda, 0x6e, 0x96, 0x98, 0xa8, 0x14, 0xbb, 0xf3, 0xe0,
	0x17, 0xb0, 0xf9, 0xca, 0xd7, 0xe7, 0xf4, 0x84, 0xca, 0xcf, 0xda, 0x86, 0x5a, 0xf1, 0xfd, 0x61,
	0x17, 0x0b, 0xd9, 0x5d, 0x7e, 0x7f, 0x76, 0x0f, 0xfe, 0x5d, 0x86, 0xf6, 0x73, 0x39, 0xca, 0xb5,
	0xfe, 0x0a, 0xb6, 0x8d, 0xaf, 0xcf, 0xed, 0x4b, 0x2e, 0xcf, 0x79, 0xdd, 0x2f, 0x11, 0x18, 0x07,
	0xf3, 0x9b, 0xc8, 0x76, 0x0c, 0xaf, 0x59, 0xe6, 0x32, 0x83, 0x99, 0x6b, 0x0c, 0x76, 0x0c, 0xeb,
	0x38, 0x35, 0xce, 0xd5, 0xda, 0xfc, 0xfa, 0xce, 0x0a, 0xb5, 0x05, 0x73, 0x9d, 0xc2, 0x8e, 0x2a,
	0x90, 0xf6, 0x38, 0xdc, 0x78, 0xc7, 0xc9, 0x2b, 0x02, 0x79, 0xb8, 0x98, 0x1c, 0xfd, 0x6c, 0x70,
	0x58, 0x56, 0x50, 0xcc, 0x92, 0x53, 0xd8, 0xbc, 0x66, 0xc3, 0x0a, 0xd5, 0xfb, 0x8b, 0xaa, 0x57,
	0xa1, 0x5d, 0xc8, 0x9b, 0x3f, 0x94, 0xa0, 0x3b, 0x6f, 0xa2, 0xe2, 0x64, 0xe6, 0xc7, 0xd7, 0x2b,
	0x51, 0xb5, 0x58, 0x89, 0xde, 0x7d, 0xa1, 0x05, 0xb4, 0x0a, 0xe5, 0x7a, 0x1f, 0x2a, 0x53, 0x39,
	0xa2, 0xc0, 0x7a, 0x77, 0xf0, 0xa2, 0xc8, 0xe0, 0x2f, 0x0b, 0xb6, 0x50, 0xf7, 0x7e, 0x6f, 0x55,
	0xfc, 0xa6, 0x89, 0xa4, 0x66, 0x7e, 0xbc, 0x64, 0xcb, 0x92, 0xfb, 0x1e, 0xc9, 0xb0, 0x21, 0x00,
	0xce, 0x1e, 0x94, 0xd8, 0xda, 0x95, 0xc9, 0x6b, 0x79, 0xdf, 0x9a, 0xba, 0x2f, 0x3d, 0x78, 0x00,
	0x4d, 0x4f, 0x68, 0x25, 0x63, 0x2d, 0xb0, 0xcc, 0xe8, 0x74, 0x8c, 0xbd, 0x9d, 0x4c, 0x6e, 0x7a,
	0xd9, 0x12, 0xf3, 0xd1, 0x8d, 0x5c, 0xee, 0x4f, 0x20, 0xbb, 0x1a, 0xfc, 0xbe, 0x04, 0xbd, 0x79,
	0xe5, 0x70, 0x6a, 0x3e, 0x21, 0xa4, 0xe9, 0x9b, 0xf4, 0xcc, 0x0d, 0xc8, 0x44, 0xbc, 0x5c, 0x80,
	0x3d, 0x01, 0x56, 0x98, 0x95, 0x04, 0x47, 0x27, 0xb2, 0x70, 0x7e, 0x97, 0xa7, 0xbd, 0xe9, 0x22,
	0x41, 0x0f, 0x86, 0xb0, 0x39, 0x7f, 0x05, 0x64, 0x25, 0xcc, 0xfd, 0xab, 0x55, 0x78, 0x93, 0xe0,
	0x74, 0xff, 0x45, 0x1a, 0x06, 0x83, 0x11, 0xb0, 0xa2, 0xfc, 0xff, 0x62, 0xf8, 0x2d, 0x68, 0xbb,
	0xb7, 0x04, 0xea, 0x70, 0xb8, 0xc0, 0x34, 0xd7, 0x7a, 0xf0, 0xaf, 0x12, 0xb4, 0x0b, 0xef, 0x04,
	0xb6, 0x0b, 0x3b, 0xd9, 0x80, 0xcd, 0x69, 0xc0, 0xe7, 0x76, 0xc2, 0xef, 0xad, 0xb1, 0x6d, 0xe8,
	0x65, 0x43, 0x3c, 0x77, 0x73, 0x72, 0xaf, 0xc4, 0xfa, 0xb0, 0x9d, 0x6f, 0x38, 0x15, 0x26, 0xe7,
	0x94, 0xd9, 0x26, 0xac, 0xd3, 0x8c, 0x9d, 0x93, 0x2a, 0xac, 0x07, 0x1d, 0x37, 0x3b, 0x73, 0x1c,
	0x71, 0x7b, 0x55, 0xb6, 0x45, 0x51, 0xc9, 0x71, 0x2e, 0xe6, 0x76, 0x30, 0xee, 0xd5, 0xd8, 0x0d,
	0xd8, 0x2a, 0xc6, 0x29, 0xf7, 0x84, 0x4e, 0x67, 0xa6, 0x57, 0x67, 0x4d, 0xa8, 0xa2, 0x95, 0xbd,
	0x06, 0xeb, 0x50, 0x44, 0x50, 0x12, 0xf4, 0x9a, 0xa8, 0x65, 0xde, 0xe3, 0x38, 0x36, 0xb9, 0x5e,
	0x0b, 0x0f, 0x2b, 0x6a, 0xe9, 0xc1, 0xe1, 0xdf, 0x4a, 0x50, 0x7b, 0x84, 0xc6, 0xb2, 0x07, 0xd0,
	0x55, 0x22, 0xd1, 0xa1, 0x36, 0x19, 0x36, 0x6c, 0x73, 0xe1, 0x91, 0x85, 0xa4, 0xbd, 0x0f, 0x86,
	0xf6, 0xcf, 0xd0, 0x61, 0xf6, 0x67, 0xe8, 0xf0, 0x69, 0xa4, 0xcc, 0x15, 0xfb, 0x11, 0x34, 0xb3,
	0x50, 0x60, 0xcb, 0x49, 0xe7, 0xee, 0x75, 0xef, 0xc6, 0x35, 0xba, 0xbb, 0x92, 0x67, 0xd0, 0x9d,
	0x08, 0xc3, 0x0b, 0xd7, 0xc2, 0xfa, 0xd7, 0x8e, 0xce, 0xb4, 0xec, 0xae, 0xe0, 0x58, 0x3d, 0x8f,
	0x6e, 0xfe, 0x72, 0x2f, 0xfb, 0x33, 0x77, 0xe2, 0xfe, 0xc9, 0xbd, 0xaf, 0xce, 0x27, 0xee, 0x8f,
	0xdb, 0x3a, 0xfd, 0x7c, 0xff, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x87, 0x32, 0x07, 0xf1,
	0x15, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BrainClient is the client API for Brain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BrainClient interface {
	PersistMetrics(ctx context.Context, in *JobMetrics, opts ...grpc.CallOption) (*empty.Empty, error)
	Optimize(ctx context.Context, in *OptimizeRequest, opts ...grpc.CallOption) (*OptimizeResponse, error)
	GetJobMetrics(ctx context.Context, in *JobMetricsRequest, opts ...grpc.CallOption) (*JobMetricsResponse, error)
}

type brainClient struct {
	cc *grpc.ClientConn
}

func NewBrainClient(cc *grpc.ClientConn) BrainClient {
	return &brainClient{cc}
}

func (c *brainClient) PersistMetrics(ctx context.Context, in *JobMetrics, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.Brain/persist_metrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainClient) Optimize(ctx context.Context, in *OptimizeRequest, opts ...grpc.CallOption) (*OptimizeResponse, error) {
	out := new(OptimizeResponse)
	err := c.cc.Invoke(ctx, "/proto.Brain/optimize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainClient) GetJobMetrics(ctx context.Context, in *JobMetricsRequest, opts ...grpc.CallOption) (*JobMetricsResponse, error) {
	out := new(JobMetricsResponse)
	err := c.cc.Invoke(ctx, "/proto.Brain/get_job_metrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrainServer is the server API for Brain service.
type BrainServer interface {
	PersistMetrics(context.Context, *JobMetrics) (*empty.Empty, error)
	Optimize(context.Context, *OptimizeRequest) (*OptimizeResponse, error)
	GetJobMetrics(context.Context, *JobMetricsRequest) (*JobMetricsResponse, error)
}

// UnimplementedBrainServer can be embedded to have forward compatible implementations.
type UnimplementedBrainServer struct {
}

func (*UnimplementedBrainServer) PersistMetrics(ctx context.Context, req *JobMetrics) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PersistMetrics not implemented")
}
func (*UnimplementedBrainServer) Optimize(ctx context.Context, req *OptimizeRequest) (*OptimizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Optimize not implemented")
}
func (*UnimplementedBrainServer) GetJobMetrics(ctx context.Context, req *JobMetricsRequest) (*JobMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobMetrics not implemented")
}

func RegisterBrainServer(s *grpc.Server, srv BrainServer) {
	s.RegisterService(&_Brain_serviceDesc, srv)
}

func _Brain_PersistMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobMetrics)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainServer).PersistMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Brain/PersistMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainServer).PersistMetrics(ctx, req.(*JobMetrics))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brain_Optimize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainServer).Optimize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Brain/Optimize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainServer).Optimize(ctx, req.(*OptimizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brain_GetJobMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainServer).GetJobMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Brain/GetJobMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainServer).GetJobMetrics(ctx, req.(*JobMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Brain_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Brain",
	HandlerType: (*BrainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "persist_metrics",
			Handler:    _Brain_PersistMetrics_Handler,
		},
		{
			MethodName: "optimize",
			Handler:    _Brain_Optimize_Handler,
		},
		{
			MethodName: "get_job_metrics",
			Handler:    _Brain_GetJobMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dlrover/proto/brain.proto",
}
