---
apiVersion: v1
kind: Service
metadata:
  name: dlrover-brain
  namespace: dlrover
spec:
  type: NodePort
  ports:
    - port: 50002
      protocol: TCP
      targetPort: 50002
  selector:
    app: dlrover-brain

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dlrover-brain
  name: dlrover-brain
  namespace: dlrover
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dlrover-brain
  template:
    metadata:
      labels:
        app: dlrover-brain
      name: dlrover-brain
      namespace: dlrover
    spec:
      serviceAccountName: dlrover-controller-manager
      volumes:
        - name: pvc-nas
          persistentVolumeClaim:
            claimName: elastic-train-pvc-dlrover
      containers:
        - command:
            - /bin/bash
            - -c
            - (python -m dlrover.brain.python.server.server -alsologtostderr \
              --namespace dlrover --port 50002 2>&1) |
              tee /data/logs/brain-logs/brain.log; exit ${PIPESTATUS[0]}
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: TZ
            value: Asia/Shanghai
          - name: PYTHONPATH
            value: $PYTHONPATH:$(pwd)
          image: registry.cic.cmbchina.cn/cic-arm/cmb-neotrain-dlrover-brain:master-v0.7.0-hw-20260212
          imagePullPolicy: IfNotPresent
          name: dlrover-brain
          ports:
            - containerPort: 50002
              protocol: TCP
          volumeMounts:
            - name: pvc-nas
              mountPath: /data
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
