---
name: tfplus-python-test
description: run pytest to execute python test cases of tfplus python
runs:
  using: 'docker'
  image: "easydl/tfplus:tf212_dev"
  args:
    - "/bin/bash"
    - "-c"
    - "pip install pytest \
&& cd tfplus \
&& PYTHONPATH=. pytest tfplus/tests"
