# Customize values for dlrover.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry: "registry.cn-hangzhou.aliyuncs.com"
    
topoMapper:
  topology_config: |

controller:
  image:
    name: "elasticjob-controller"
    tag: "v0.7.0"

rbacProxy:
  image:
    name: "docker.io/kubebuilder/kube-rbac-proxy"
    tag: "v0.13.1"

dlroverMaster:
  image:
    name: "dlrover-master"
    tag: "v0.7.0"