---
name: dlrover-trainer-test-criteo-deeprec
description: run pytest to execute python test cases of dlrover-trainer
runs:
  using: 'docker'
  image: "easydl/dlrover:deeprec_ci"
  args:
    - "/bin/bash"
    - "-c"
    - " python -m grpc_tools.protoc -I. \
dlrover/proto/*.proto --python_out=. --grpc_python_out=. \
&& export PYTHONPATH=`pwd` \
&& cd examples/tensorflow/criteo_deeprec\
&& unset DLROVER_MASTER_ADDR  && sh run.sh"
