# permissions for end users to edit elasticjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticjob-editor-role
rules:
- apiGroups:
  - elastic.iml.github.io
  resources:
  - elasticjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elastic.iml.github.io
  resources:
  - elasticjobs/status
  verbs:
  - get
