/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/intelligent-machine-learning/easydl/dlrover/go/operator/api/elastic.iml.github.io/v1alpha1"
	scheme "github.com/intelligent-machine-learning/easydl/dlrover/go/operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ElasticJobsGetter has a method to return a ElasticJobInterface.
// A group's client should implement this interface.
type ElasticJobsGetter interface {
	ElasticJobs(namespace string) ElasticJobInterface
}

// ElasticJobInterface has methods to work with ElasticJob resources.
type ElasticJobInterface interface {
	Create(ctx context.Context, elasticJob *v1alpha1.ElasticJob, opts v1.CreateOptions) (*v1alpha1.ElasticJob, error)
	Update(ctx context.Context, elasticJob *v1alpha1.ElasticJob, opts v1.UpdateOptions) (*v1alpha1.ElasticJob, error)
	UpdateStatus(ctx context.Context, elasticJob *v1alpha1.ElasticJob, opts v1.UpdateOptions) (*v1alpha1.ElasticJob, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ElasticJob, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ElasticJobList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ElasticJob, err error)
	ElasticJobExpansion
}

// elasticJobs implements ElasticJobInterface
type elasticJobs struct {
	client rest.Interface
	ns     string
}

// newElasticJobs returns a ElasticJobs
func newElasticJobs(c *ElasticV1alpha1Client, namespace string) *elasticJobs {
	return &elasticJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the elasticJob, and returns the corresponding elasticJob object, and an error if there is any.
func (c *elasticJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ElasticJob, err error) {
	result = &v1alpha1.ElasticJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("elasticjobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ElasticJobs that match those selectors.
func (c *elasticJobs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ElasticJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ElasticJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("elasticjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested elasticJobs.
func (c *elasticJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("elasticjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a elasticJob and creates it.  Returns the server's representation of the elasticJob, and an error, if there is any.
func (c *elasticJobs) Create(ctx context.Context, elasticJob *v1alpha1.ElasticJob, opts v1.CreateOptions) (result *v1alpha1.ElasticJob, err error) {
	result = &v1alpha1.ElasticJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("elasticjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(elasticJob).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a elasticJob and updates it. Returns the server's representation of the elasticJob, and an error, if there is any.
func (c *elasticJobs) Update(ctx context.Context, elasticJob *v1alpha1.ElasticJob, opts v1.UpdateOptions) (result *v1alpha1.ElasticJob, err error) {
	result = &v1alpha1.ElasticJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("elasticjobs").
		Name(elasticJob.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(elasticJob).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *elasticJobs) UpdateStatus(ctx context.Context, elasticJob *v1alpha1.ElasticJob, opts v1.UpdateOptions) (result *v1alpha1.ElasticJob, err error) {
	result = &v1alpha1.ElasticJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("elasticjobs").
		Name(elasticJob.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(elasticJob).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the elasticJob and deletes it. Returns an error if one occurs.
func (c *elasticJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("elasticjobs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *elasticJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("elasticjobs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched elasticJob.
func (c *elasticJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ElasticJob, err error) {
	result = &v1alpha1.ElasticJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("elasticjobs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
