workspace(name="atorch")

load("//third_party/brpc:brpc_workspace.bzl", "brpc_workspace")
brpc_workspace();

load("//third_party/cuda:cuda_workspace.bzl", "cuda_workspace")
cuda_workspace();

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")
http_archive(
    name = "com_github_jupp0r_prometheus_cpp",
    strip_prefix = "prometheus-cpp-1.2.4",
    urls = ["https://github.com/jupp0r/prometheus-cpp/archive/v1.2.4.zip"],
)
load("@com_github_jupp0r_prometheus_cpp//bazel:repositories.bzl", "prometheus_cpp_repositories")
prometheus_cpp_repositories()
