# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import coworker_pb2 as coworker__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class CoworkerRpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_batch_data = channel.unary_unary(
                '/protos.CoworkerRpcService/get_batch_data',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=coworker__pb2.BatchData.FromString,
                )


class CoworkerRpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_batch_data(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoworkerRpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_batch_data': grpc.unary_unary_rpc_method_handler(
                    servicer.get_batch_data,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=coworker__pb2.BatchData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.CoworkerRpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CoworkerRpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_batch_data(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.CoworkerRpcService/get_batch_data',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            coworker__pb2.BatchData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class DataInfoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.report_data_info = channel.unary_unary(
                '/protos.DataInfoService/report_data_info',
                request_serializer=coworker__pb2.DataInfo.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.get_data_info = channel.unary_unary(
                '/protos.DataInfoService/get_data_info',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=coworker__pb2.DataInfo.FromString,
                )


class DataInfoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def report_data_info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_data_info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataInfoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'report_data_info': grpc.unary_unary_rpc_method_handler(
                    servicer.report_data_info,
                    request_deserializer=coworker__pb2.DataInfo.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'get_data_info': grpc.unary_unary_rpc_method_handler(
                    servicer.get_data_info,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=coworker__pb2.DataInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.DataInfoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataInfoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def report_data_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.DataInfoService/report_data_info',
            coworker__pb2.DataInfo.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_data_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.DataInfoService/get_data_info',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            coworker__pb2.DataInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
