# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coworker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='coworker.proto',
  package='protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x63oworker.proto\x12\x06protos\x1a\x1bgoogle/protobuf/empty.proto\"\x19\n\tBatchData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"4\n\x08\x44\x61taInfo\x12\x15\n\rcoworker_addr\x18\x01 \x01(\t\x12\x11\n\tbatch_num\x18\x02 \x01(\x05\x32Q\n\x12\x43oworkerRpcService\x12;\n\x0eget_batch_data\x12\x16.google.protobuf.Empty\x1a\x11.protos.BatchData2\x8a\x01\n\x0f\x44\x61taInfoService\x12<\n\x10report_data_info\x12\x10.protos.DataInfo\x1a\x16.google.protobuf.Empty\x12\x39\n\rget_data_info\x12\x16.google.protobuf.Empty\x1a\x10.protos.DataInfob\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_BATCHDATA = _descriptor.Descriptor(
  name='BatchData',
  full_name='protos.BatchData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='protos.BatchData.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=80,
)


_DATAINFO = _descriptor.Descriptor(
  name='DataInfo',
  full_name='protos.DataInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='coworker_addr', full_name='protos.DataInfo.coworker_addr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_num', full_name='protos.DataInfo.batch_num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['BatchData'] = _BATCHDATA
DESCRIPTOR.message_types_by_name['DataInfo'] = _DATAINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BatchData = _reflection.GeneratedProtocolMessageType('BatchData', (_message.Message,), {
  'DESCRIPTOR' : _BATCHDATA,
  '__module__' : 'coworker_pb2'
  # @@protoc_insertion_point(class_scope:protos.BatchData)
  })
_sym_db.RegisterMessage(BatchData)

DataInfo = _reflection.GeneratedProtocolMessageType('DataInfo', (_message.Message,), {
  'DESCRIPTOR' : _DATAINFO,
  '__module__' : 'coworker_pb2'
  # @@protoc_insertion_point(class_scope:protos.DataInfo)
  })
_sym_db.RegisterMessage(DataInfo)



_COWORKERRPCSERVICE = _descriptor.ServiceDescriptor(
  name='CoworkerRpcService',
  full_name='protos.CoworkerRpcService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=136,
  serialized_end=217,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_batch_data',
    full_name='protos.CoworkerRpcService.get_batch_data',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_BATCHDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COWORKERRPCSERVICE)

DESCRIPTOR.services_by_name['CoworkerRpcService'] = _COWORKERRPCSERVICE


_DATAINFOSERVICE = _descriptor.ServiceDescriptor(
  name='DataInfoService',
  full_name='protos.DataInfoService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=220,
  serialized_end=358,
  methods=[
  _descriptor.MethodDescriptor(
    name='report_data_info',
    full_name='protos.DataInfoService.report_data_info',
    index=0,
    containing_service=None,
    input_type=_DATAINFO,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_data_info',
    full_name='protos.DataInfoService.get_data_info',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_DATAINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATAINFOSERVICE)

DESCRIPTOR.services_by_name['DataInfoService'] = _DATAINFOSERVICE

# @@protoc_insertion_point(module_scope)
