/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	elasticimlgithubiov1alpha1 "github.com/intelligent-machine-learning/easydl/dlrover/go/operator/api/elastic.iml.github.io/v1alpha1"
	versioned "github.com/intelligent-machine-learning/easydl/dlrover/go/operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/intelligent-machine-learning/easydl/dlrover/go/operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/intelligent-machine-learning/easydl/dlrover/go/operator/pkg/client/listers/elastic.iml.github.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ScalePlanInformer provides access to a shared informer and lister for
// ScalePlans.
type ScalePlanInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ScalePlanLister
}

type scalePlanInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewScalePlanInformer constructs a new informer for ScalePlan type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewScalePlanInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredScalePlanInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredScalePlanInformer constructs a new informer for ScalePlan type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredScalePlanInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ElasticV1alpha1().ScalePlans(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ElasticV1alpha1().ScalePlans(namespace).Watch(context.TODO(), options)
			},
		},
		&elasticimlgithubiov1alpha1.ScalePlan{},
		resyncPeriod,
		indexers,
	)
}

func (f *scalePlanInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredScalePlanInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *scalePlanInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&elasticimlgithubiov1alpha1.ScalePlan{}, f.defaultInformer)
}

func (f *scalePlanInformer) Lister() v1alpha1.ScalePlanLister {
	return v1alpha1.NewScalePlanLister(f.Informer().GetIndexer())
}
