---
name: dlrover-python-test
description: run pytest to execute python test cases of dlrover python
runs:
  using: 'docker'
  image: "easydl/dlrover:ci"
  args:
    - "/bin/bash"
    - "-c"
    - "pip install kubernetes grpcio-tools psutil deprecated \
'ray[default]' pyhocon pytest-cov tensorflow==2.13.0 \
&& pip install torch==2.0.1+cpu -f \
https://download.pytorch.org/whl/torch_stable.html \
&& python -m grpc_tools.protoc -I. \
dlrover/proto/*.proto --python_out=. --grpc_python_out=. \
&& python -m pytest dlrover/python/tests dlrover/trainer/tests \
--cov-report xml --cov=dlrover "
