# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import acceleration_pb2 as acceleration__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class AutoAccelerationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_task = channel.unary_unary(
                '/proto.AutoAccelerationService/get_task',
                request_serializer=acceleration__pb2.GetAutoAccelerationTaskRequest.SerializeToString,
                response_deserializer=acceleration__pb2.AutoAccelerationTask.FromString,
                )
        self.report_task_result = channel.unary_unary(
                '/proto.AutoAccelerationService/report_task_result',
                request_serializer=acceleration__pb2.AutoAccelerationTaskResult.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class AutoAccelerationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_task(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def report_task_result(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AutoAccelerationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_task': grpc.unary_unary_rpc_method_handler(
                    servicer.get_task,
                    request_deserializer=acceleration__pb2.GetAutoAccelerationTaskRequest.FromString,
                    response_serializer=acceleration__pb2.AutoAccelerationTask.SerializeToString,
            ),
            'report_task_result': grpc.unary_unary_rpc_method_handler(
                    servicer.report_task_result,
                    request_deserializer=acceleration__pb2.AutoAccelerationTaskResult.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.AutoAccelerationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AutoAccelerationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_task(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.AutoAccelerationService/get_task',
            acceleration__pb2.GetAutoAccelerationTaskRequest.SerializeToString,
            acceleration__pb2.AutoAccelerationTask.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def report_task_result(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.AutoAccelerationService/report_task_result',
            acceleration__pb2.AutoAccelerationTaskResult.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
