# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: acceleration.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61\x63\x63\x65leration.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"4\n\x1eGetAutoAccelerationTaskRequest\x12\x12\n\nprocess_id\x18\x01 \x01(\x05\"C\n\x12OptimizationMethod\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x63onfig\x18\x02 \x01(\x0c\x12\x0f\n\x07tunable\x18\x03 \x01(\x08\"2\n\x08Strategy\x12&\n\x03opt\x18\x01 \x03(\x0b\x32\x19.proto.OptimizationMethod\"\x1f\n\x0e\x41nalysisMethod\x12\r\n\x05names\x18\x01 \x03(\t\"\xe7\x01\n\x14\x41utoAccelerationTask\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\x14\n\x0cprocess_mode\x18\x03 \x01(\t\x12#\n\x08strategy\x18\x04 \x01(\x0b\x32\x0f.proto.StrategyH\x00\x12\x30\n\x0f\x61nalysis_method\x18\x05 \x01(\x0b\x32\x15.proto.AnalysisMethodH\x00\x12\x1d\n\x13parallel_group_info\x18\x06 \x01(\x0cH\x00\x12\x12\n\ntime_limit\x18\x07 \x01(\x05\x42\x0b\n\ttask_info\"\xc2\x01\n\x1a\x41utoAccelerationTaskResult\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\x12\n\nprocess_id\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\x08\x12#\n\x08strategy\x18\x04 \x01(\x0b\x32\x0f.proto.StrategyH\x00\x12\x14\n\nmodel_meta\x18\x05 \x01(\x0cH\x00\x12\x17\n\rdryrun_result\x18\x06 \x01(\x0cH\x00\x12\x11\n\ttask_type\x18\x07 \x01(\tB\x08\n\x06result2\xba\x01\n\x17\x41utoAccelerationService\x12N\n\x08get_task\x12%.proto.GetAutoAccelerationTaskRequest\x1a\x1b.proto.AutoAccelerationTask\x12O\n\x12report_task_result\x12!.proto.AutoAccelerationTaskResult\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'acceleration_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GETAUTOACCELERATIONTASKREQUEST']._serialized_start=58
  _globals['_GETAUTOACCELERATIONTASKREQUEST']._serialized_end=110
  _globals['_OPTIMIZATIONMETHOD']._serialized_start=112
  _globals['_OPTIMIZATIONMETHOD']._serialized_end=179
  _globals['_STRATEGY']._serialized_start=181
  _globals['_STRATEGY']._serialized_end=231
  _globals['_ANALYSISMETHOD']._serialized_start=233
  _globals['_ANALYSISMETHOD']._serialized_end=264
  _globals['_AUTOACCELERATIONTASK']._serialized_start=267
  _globals['_AUTOACCELERATIONTASK']._serialized_end=498
  _globals['_AUTOACCELERATIONTASKRESULT']._serialized_start=501
  _globals['_AUTOACCELERATIONTASKRESULT']._serialized_end=695
  _globals['_AUTOACCELERATIONSERVICE']._serialized_start=698
  _globals['_AUTOACCELERATIONSERVICE']._serialized_end=884
# @@protoc_insertion_point(module_scope)
