# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coworker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63oworker.proto\x12\x06protos\x1a\x1bgoogle/protobuf/empty.proto\"\x19\n\tBatchData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"4\n\x08\x44\x61taInfo\x12\x15\n\rcoworker_addr\x18\x01 \x01(\t\x12\x11\n\tbatch_num\x18\x02 \x01(\x05\x32Q\n\x12\x43oworkerRpcService\x12;\n\x0eget_batch_data\x12\x16.google.protobuf.Empty\x1a\x11.protos.BatchData2\x8a\x01\n\x0f\x44\x61taInfoService\x12<\n\x10report_data_info\x12\x10.protos.DataInfo\x1a\x16.google.protobuf.Empty\x12\x39\n\rget_data_info\x12\x16.google.protobuf.Empty\x1a\x10.protos.DataInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coworker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_BATCHDATA']._serialized_start=55
  _globals['_BATCHDATA']._serialized_end=80
  _globals['_DATAINFO']._serialized_start=82
  _globals['_DATAINFO']._serialized_end=134
  _globals['_COWORKERRPCSERVICE']._serialized_start=136
  _globals['_COWORKERRPCSERVICE']._serialized_end=217
  _globals['_DATAINFOSERVICE']._serialized_start=220
  _globals['_DATAINFOSERVICE']._serialized_end=358
# @@protoc_insertion_point(module_scope)
