---
name: atorch-python-test
description: run pytest to execute python test cases of atorch python
runs:
  using: 'docker'
  image: "easydl/atorch:iml_20230918"
  args:
    - "/bin/bash"
    - "-c"
    - "pip install pytest fairscale==0.4.1\
&& echo -e 'import math\ninf = math.inf\nnan = math.nan\nstring_classes = \
(str, bytes)' > /opt/conda/lib/python3.8/site-packages/torch/_six.py \
&& cd atorch \
&& sh bin/build_proto.sh \
&& PYTHONPATH=. pytest atorch/tests"
