---
name: atorch-python-test
description: run pytest to execute python test cases of atorch python
runs:
  using: 'docker'
  image: "easydl/atorch:iml"
  args:
    - "/bin/bash"
    - "-c"
    - "pip install pytest \
&& cd atorch \
&& PYTHONPATH=. pytest atorch/tests"
