name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    runs:
      using: 'docker'
      image: 'elasticdl/elasticdl:dev'
      entrypoint: 'pre-commit run -a'
