---
name: atorch-pre-commit
description: run pre-commit to check codes for atorch
runs:
  using: 'docker'
  image: "easydl/atorch:iml"
  args:
    - "/bin/bash"
    - "-c"
    - "pip install pytest \
&& cd atorch \
&& sh dev/scripts/pre-commit.sh"
